version = 1

[tools.boss]
target = "//tools/boss/cli:boss"

[tools.bossctl]
target = "//tools/boss/bossctl:bossctl"

[tools.checkleft]
target = "//tools/checkleft:checkleft"

[tools.checks]
target = "//tools/checkleft:checkleft"

[tools.cube]
target = "//tools/cube:cube"

[tools.hood]
target = "//tools/hood:hood"
