//! Guest SDK for authoring checkleft checks as WebAssembly Component Model components.
//!
//! Check authors write a plain Rust function over SDK types, annotate it with
//! `#[check]`, and call `export_checks!` once at the crate root. The SDK
//! generates the component ABI boilerplate so authors never touch WIT bindings.
//!
//! # Quick start
//!
//! ```rust,ignore
//! use checkleft_check_sdk::{check, export_checks, CheckInput, Finding};
//!
//! #[check(name = "my-check")]
//! fn my_check(input: CheckInput) -> Vec<Finding> {
//!     // Read config:
//!     // let cfg: MyConfig = input.config().unwrap_or_default();
//!     // Read files via std::fs — the sandbox root is preopened by the host.
//!     vec![]
//! }
//!
//! export_checks!(my_check);
//! ```
//!
//! The check crate's `Cargo.toml` must also include `wit-bindgen = "0.51"` as a
//! direct dependency; `export_checks!` expands to a `wit_bindgen::generate!` call.

// Re-export the proc macros so check authors only need `checkleft-check-sdk`.
pub use checkleft_check_sdk_macro::{check, export_checks};

// ── Public types ─────────────────────────────────────────────────────────────

/// How a file changed relative to the prior revision.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChangeKind {
    Added,
    Modified,
    Deleted,
    Renamed,
}

/// A single file that changed in the current changeset.
#[derive(Debug, Clone)]
pub struct ChangedFile {
    pub path: String,
    pub kind: ChangeKind,
    /// Set only when `kind == ChangeKind::Renamed`.
    pub old_path: Option<String>,
}

/// One contiguous hunk of a unified diff.
#[derive(Debug, Clone, Copy)]
pub struct DiffHunk {
    pub old_start: u32,
    pub old_lines: u32,
    pub new_start: u32,
    pub new_lines: u32,
    pub added_lines: u32,
    pub removed_lines: u32,
}

/// Diff hunks for a single file.
#[derive(Debug, Clone)]
pub struct FileDiff {
    pub path: String,
    pub hunks: Vec<DiffHunk>,
}

/// The set of changes under review.
#[derive(Debug, Clone)]
pub struct ChangeSet {
    pub changed_files: Vec<ChangedFile>,
    pub file_diffs: Vec<FileDiff>,
    pub commit_description: Option<String>,
    pub pr_description: Option<String>,
    pub change_id: Option<String>,
    pub repository: Option<String>,
}

/// All input a check receives for one invocation.
#[derive(Debug, Clone)]
pub struct CheckInput {
    pub changeset: ChangeSet,
    config_json: String,
    /// Repo-root-relative directory of the CHECKS file that configures this
    /// check (e.g. `"tools/checkleft"` or `""` for the repo root).
    /// Use this to scope `exclude_files` patterns to the config subtree so
    /// that patterns only match files beneath the CHECKS file's directory.
    pub config_dir: String,
}

impl CheckInput {
    /// Deserialize the per-check configuration into `T`.
    ///
    /// The host passes config as a JSON string (`config-json` in the WIT
    /// contract). This helper deserializes it into the author's own
    /// `#[derive(Deserialize)]` config struct via serde.
    pub fn config<T: serde::de::DeserializeOwned>(&self) -> Result<T, serde_json::Error> {
        serde_json::from_str(&self.config_json)
    }

    /// Construct a `CheckInput` from raw WIT-lifted parts.
    ///
    /// Called by the code generated by `export_checks!`. Not part of the
    /// public API and subject to change without notice.
    #[doc(hidden)]
    pub fn __from_parts(changeset: ChangeSet, config_json: String, config_dir: String) -> Self {
        CheckInput {
            changeset,
            config_json,
            config_dir,
        }
    }
}

/// Diagnostic severity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
    Info,
}

/// Source location attached to a finding.
#[derive(Debug, Clone)]
pub struct Location {
    pub path: String,
    pub line: Option<u32>,
    pub column: Option<u32>,
}

/// A single text substitution within a file.
#[derive(Debug, Clone)]
pub struct FileEdit {
    pub path: String,
    pub old_text: String,
    pub new_text: String,
}

/// An optional automated fix for a finding.
#[derive(Debug, Clone)]
pub struct SuggestedFix {
    pub description: String,
    pub edits: Vec<FileEdit>,
}

/// One diagnostic produced by a check.
#[derive(Debug, Clone)]
pub struct Finding {
    pub severity: Severity,
    pub message: String,
    pub location: Option<Location>,
    pub remediations: Vec<String>,
    pub suggested_fix: Option<SuggestedFix>,
}

impl Finding {
    /// Create an error-severity finding with the given message.
    pub fn error(message: impl Into<String>) -> Self {
        Self::with_severity(Severity::Error, message)
    }

    /// Create a warning-severity finding with the given message.
    pub fn warning(message: impl Into<String>) -> Self {
        Self::with_severity(Severity::Warning, message)
    }

    /// Create an info-severity finding with the given message.
    pub fn info(message: impl Into<String>) -> Self {
        Self::with_severity(Severity::Info, message)
    }

    fn with_severity(severity: Severity, message: impl Into<String>) -> Self {
        Finding {
            severity,
            message: message.into(),
            location: None,
            remediations: vec![],
            suggested_fix: None,
        }
    }

    /// Attach a file/line location to this finding.
    pub fn at(mut self, path: impl Into<String>, line: u32) -> Self {
        self.location = Some(Location {
            path: path.into(),
            line: Some(line),
            column: None,
        });
        self
    }

    /// Attach a file/line/column location to this finding.
    pub fn at_column(mut self, path: impl Into<String>, line: u32, column: u32) -> Self {
        self.location = Some(Location {
            path: path.into(),
            line: Some(line),
            column: Some(column),
        });
        self
    }

    /// Add a remediation hint to this finding.
    pub fn with_remediation(mut self, hint: impl Into<String>) -> Self {
        self.remediations.push(hint.into());
        self
    }
}

/// An exclusion entry declared by a check for stale-exclusion auditing.
///
/// Returned by `CheckEntry::declared_exclusions`. The host re-evaluates the
/// exclusion via `CheckEntry::evaluate_exclusion` when a path in `depends_on`
/// appears in the changeset.
#[derive(Debug, Clone)]
pub struct DeclaredExclusion {
    /// The exclusion entry exactly as written in the CHECKS file.
    pub entry: String,
    /// Config-file-relative paths this exclusion depends on.
    /// An empty vec means the exclusion is never audited (fail-safe).
    pub depends_on: Vec<String>,
}

/// The verdict for a single exclusion re-evaluated as if it were not present.
///
/// Checks must fail safe: when staleness cannot be proven, return `Unknown`
/// rather than `Stale`. A false stale finding trains authors to ignore the check;
/// a missed one merely leaves a dead entry for next time.
#[derive(Debug, Clone)]
pub enum ExclusionStatus {
    /// The exclusion is still required: the target still violates the rule.
    LoadBearing,
    /// The exclusion is no longer required. Contains a short human reason.
    Stale(String),
    /// Staleness could not be determined. Fail-safe default.
    Unknown,
}

/// Declares how much of the repository a check needs to read.
///
/// Returned by `#[check(access_scope = ...)]` and stored in `CheckDescriptor`.
/// `None` in `CheckDescriptor.access_scope` means `modified-only` (the default).
#[derive(Debug, Clone)]
pub enum AccessScope {
    /// Only the files modified in the current changeset (the default).
    ModifiedOnly,
    /// Every file in the repository tree. Explicit opt-in.
    WholeRepo,
    /// Modified files plus files matched by the given repo-root-relative globs.
    Globs(Vec<String>),
}

/// Self-description returned by `list-checks`.
#[derive(Debug, Clone)]
pub struct CheckDescriptor {
    pub name: String,
    pub description: String,
    pub default_severity: Severity,
    /// `None` means `modified-only`.
    pub access_scope: Option<AccessScope>,
}

// ── Internal module used by proc-macro expansions ────────────────────────────

/// Not part of the public API. Used only by code generated by `export_checks!`.
#[doc(hidden)]
pub mod __private {
    /// Implemented by each `#[check]`-annotated function's generated companion
    /// struct. Used by `export_checks!` to build the WIT dispatch table.
    pub trait CheckEntry: Send + Sync {
        fn name(&self) -> &'static str;
        fn descriptor(&self) -> crate::CheckDescriptor;
        fn run(&self, input: crate::CheckInput) -> Vec<crate::Finding>;
    }
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_input() -> CheckInput {
        CheckInput {
            changeset: ChangeSet {
                changed_files: vec![],
                file_diffs: vec![],
                commit_description: None,
                pr_description: None,
                change_id: None,
                repository: None,
            },
            config_json: "{}".to_owned(),
            config_dir: String::new(),
        }
    }

    #[test]
    fn finding_error_builder() {
        let f = Finding::error("something is wrong");
        assert_eq!(f.severity, Severity::Error);
        assert_eq!(f.message, "something is wrong");
        assert!(f.location.is_none());
        assert!(f.remediations.is_empty());
    }

    #[test]
    fn finding_warning_at() {
        let f = Finding::warning("watch out").at("src/lib.rs", 42);
        let loc = f.location.unwrap();
        assert_eq!(loc.path, "src/lib.rs");
        assert_eq!(loc.line, Some(42));
        assert!(loc.column.is_none());
    }

    #[test]
    fn finding_with_remediation() {
        let f = Finding::info("note").with_remediation("do X").with_remediation("or Y");
        assert_eq!(f.remediations, vec!["do X", "or Y"]);
    }

    #[test]
    fn check_input_config_deserializes_struct() {
        use serde::Deserialize;

        #[derive(Deserialize)]
        struct Cfg {
            threshold: u32,
        }

        let mut input = empty_input();
        input.config_json = r#"{"threshold": 42}"#.to_owned();

        let cfg: Cfg = input.config().unwrap();
        assert_eq!(cfg.threshold, 42);
    }

    #[test]
    fn check_input_config_empty_object() {
        use serde::Deserialize;

        #[derive(Deserialize, Default)]
        struct Cfg {
            #[serde(default)]
            enabled: bool,
        }

        let input = empty_input();
        let cfg: Cfg = input.config().unwrap();
        assert!(!cfg.enabled);
    }

    #[test]
    fn check_input_config_invalid_json_returns_error() {
        use serde::Deserialize;

        #[derive(Deserialize)]
        #[allow(dead_code)]
        struct Cfg {
            x: u32,
        }

        let mut input = empty_input();
        input.config_json = "not json".to_owned();

        assert!(input.config::<Cfg>().is_err());
    }
}
