//! Guest SDK for authoring checkleft checks as WebAssembly Component Model components.
//!
//! Check authors write a plain Rust function over SDK types, annotate it with
//! `#[check]`, and call `export_checks!` once at the crate root. The SDK
//! generates the component ABI boilerplate so authors never touch WIT bindings.
//!
//! # Quick start (single-check crate)
//!
//! ```rust,ignore
//! use checkleft_check_sdk::{check, export_checks, CheckInput, Finding};
//!
//! #[check(name = "my-check")]
//! fn my_check(input: CheckInput) -> Vec<Finding> {
//!     // Read config:
//!     // let cfg: MyConfig = input.config().unwrap_or_default();
//!     // Read files via std::fs — the sandbox root is preopened by the host.
//!     vec![]
//! }
//!
//! export_checks!(my_check);
//! ```
//!
//! # Multi-check bundle (aggregating crate)
//!
//! When packaging multiple checks into one component, pass fully-qualified paths
//! instead of bare idents. Each check's stale-exclusion audit and required-files
//! hooks are picked up automatically from the `#[check]` annotation — no manual
//! `use` imports for generated statics, no repeated `exclusion_audit(...)` entries.
//!
//! ```rust,ignore
//! use checkleft_check_sdk::export_checks;
//!
//! export_checks!(
//!     my_check_crate::some_check,
//!     another_check_crate::other_check,
//! );
//! ```
//!
//! The check crate's `Cargo.toml` must also include `wit-bindgen = "0.51"` as a
//! direct dependency; `export_checks!` expands to a `wit_bindgen::generate!` call.

// Re-export the proc macros so check authors only need `checkleft-check-sdk`.
pub use checkleft_check_sdk_macro::{check, export_checks};

// ── Public types ─────────────────────────────────────────────────────────────

/// How a file changed relative to the prior revision.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChangeKind {
    Added,
    Modified,
    Deleted,
    Renamed,
}

/// A single file that changed in the current changeset.
#[derive(Debug, Clone)]
pub struct ChangedFile {
    pub path: String,
    pub kind: ChangeKind,
    /// Set only when `kind == ChangeKind::Renamed`.
    pub old_path: Option<String>,
}

/// One contiguous hunk of a unified diff.
#[derive(Debug, Clone, Copy)]
pub struct DiffHunk {
    pub old_start: u32,
    pub old_lines: u32,
    pub new_start: u32,
    pub new_lines: u32,
    pub added_lines: u32,
    pub removed_lines: u32,
}

/// Diff hunks for a single file.
#[derive(Debug, Clone)]
pub struct FileDiff {
    pub path: String,
    pub hunks: Vec<DiffHunk>,
}

/// Base-revision content of a single file.
///
/// Provided for files that were deleted or modified in the current changeset
/// when a base revision is available. Absent for added files and when running
/// in `--all` mode. Use [`ChangeSet::base_file_content`] to look up by path.
#[derive(Debug, Clone)]
pub struct BaseFile {
    pub path: String,
    pub content: String,
}

/// The set of changes under review.
#[derive(Debug, Clone)]
pub struct ChangeSet {
    pub changed_files: Vec<ChangedFile>,
    pub file_diffs: Vec<FileDiff>,
    pub commit_description: Option<String>,
    pub pr_description: Option<String>,
    pub change_id: Option<String>,
    pub repository: Option<String>,
    /// Base-revision content for deleted and modified files.
    ///
    /// Empty when no base revision is available (e.g. `--all` mode). Checks
    /// should handle the absent case by skipping base-revision enforcement.
    pub base_files: Vec<BaseFile>,
}

impl ChangeSet {
    /// Return the base-revision content for `path`, or `None` when not available.
    pub fn base_file_content(&self, path: &str) -> Option<&str> {
        self.base_files
            .iter()
            .find(|f| f.path == path)
            .map(|f| f.content.as_str())
    }
}

/// All input a check receives for one invocation.
///
/// A check sees the world purely in repo-root-relative coordinates: changeset
/// paths and finding locations are repo-relative. Directory-relative config
/// (such as `exclude_files` globs authored relative to the CHECKS file) is
/// resolved to repo-relative coordinates by the host before it reaches the
/// guest, so a check never needs — and is never given — the CHECKS file's
/// directory.
#[derive(Debug, Clone)]
pub struct CheckInput {
    pub changeset: ChangeSet,
    config_json: String,
}

impl CheckInput {
    /// Deserialize the per-check configuration into `T`.
    ///
    /// The host passes config as a JSON string (`config-json` in the WIT
    /// contract). This helper deserializes it into the author's own
    /// `#[derive(Deserialize)]` config struct via serde.
    pub fn config<T: serde::de::DeserializeOwned>(&self) -> Result<T, serde_json::Error> {
        serde_json::from_str(&self.config_json)
    }

    /// Construct a `CheckInput` from raw WIT-lifted parts.
    ///
    /// Called by the code generated by `export_checks!`. Not part of the
    /// public API and subject to change without notice.
    #[doc(hidden)]
    pub fn __from_parts(changeset: ChangeSet, config_json: String) -> Self {
        CheckInput { changeset, config_json }
    }
}

/// Diagnostic severity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
    Info,
}

/// Source location attached to a finding.
#[derive(Debug, Clone)]
pub struct Location {
    pub path: String,
    pub line: Option<u32>,
    pub column: Option<u32>,
}

/// A single text substitution within a file.
#[derive(Debug, Clone)]
pub struct FileEdit {
    pub path: String,
    pub old_text: String,
    pub new_text: String,
}

/// An optional automated fix for a finding.
#[derive(Debug, Clone)]
pub struct SuggestedFix {
    pub description: String,
    pub edits: Vec<FileEdit>,
}

/// The result of a check's fix entry point.
///
/// Returned (after conversion via [`IntoFixOutcome`]) by the `fix = fn`
/// function declared on a `#[check]`. The host maps each variant onto the
/// `fix-check` WIT result:
///
/// * [`FixOutcome::Edits`] → `ok(list<file-edit>)`: the edits the host should
///   apply. An empty list is valid (the check found nothing to change).
/// * [`FixOutcome::Failed`] → `err(failed(msg))`: the fixer ran but errored; the
///   host aborts and leaves the tree untouched.
/// * [`FixOutcome::NotFixable`] → `err(not-fixable)`: the check has no fix. This
///   is the default for any check that does not declare `fix = fn`.
#[derive(Debug, Clone)]
pub enum FixOutcome {
    /// Edits to apply (possibly empty).
    Edits(Vec<FileEdit>),
    /// The fixer failed with a human-readable reason.
    Failed(String),
    /// The check declares no fix entry point.
    NotFixable,
}

/// Conversion from a fixer function's return type into a [`FixOutcome`].
///
/// A `fix = fn` function may return either `Vec<FileEdit>` (it cannot fail) or
/// `Result<Vec<FileEdit>, String>` (it may fail with a message). This trait lets
/// the `#[check]` macro accept both shapes without the author wrapping the
/// result by hand.
pub trait IntoFixOutcome {
    /// Convert `self` into the canonical [`FixOutcome`].
    fn into_fix_outcome(self) -> FixOutcome;
}

impl IntoFixOutcome for Vec<FileEdit> {
    fn into_fix_outcome(self) -> FixOutcome {
        FixOutcome::Edits(self)
    }
}

impl IntoFixOutcome for Result<Vec<FileEdit>, String> {
    fn into_fix_outcome(self) -> FixOutcome {
        match self {
            Ok(edits) => FixOutcome::Edits(edits),
            Err(message) => FixOutcome::Failed(message),
        }
    }
}

/// One diagnostic produced by a check.
#[derive(Debug, Clone)]
pub struct Finding {
    pub severity: Severity,
    pub message: String,
    pub location: Option<Location>,
    pub remediations: Vec<String>,
    pub suggested_fix: Option<SuggestedFix>,
}

impl Finding {
    /// Create an error-severity finding with the given message.
    pub fn error(message: impl Into<String>) -> Self {
        Self::with_severity(Severity::Error, message)
    }

    /// Create a warning-severity finding with the given message.
    pub fn warning(message: impl Into<String>) -> Self {
        Self::with_severity(Severity::Warning, message)
    }

    /// Create an info-severity finding with the given message.
    pub fn info(message: impl Into<String>) -> Self {
        Self::with_severity(Severity::Info, message)
    }

    fn with_severity(severity: Severity, message: impl Into<String>) -> Self {
        Finding {
            severity,
            message: message.into(),
            location: None,
            remediations: vec![],
            suggested_fix: None,
        }
    }

    /// Attach a file/line location to this finding.
    pub fn at(mut self, path: impl Into<String>, line: u32) -> Self {
        self.location = Some(Location {
            path: path.into(),
            line: Some(line),
            column: None,
        });
        self
    }

    /// Attach a file/line/column location to this finding.
    pub fn at_column(mut self, path: impl Into<String>, line: u32, column: u32) -> Self {
        self.location = Some(Location {
            path: path.into(),
            line: Some(line),
            column: Some(column),
        });
        self
    }

    /// Add a remediation hint to this finding.
    pub fn with_remediation(mut self, hint: impl Into<String>) -> Self {
        self.remediations.push(hint.into());
        self
    }
}

/// An exclusion entry declared by a check for stale-exclusion auditing.
///
/// Returned by `CheckEntry::declared_exclusions`. The host re-evaluates the
/// exclusion via `CheckEntry::evaluate_exclusion` when a path in `depends_on`
/// appears in the changeset.
#[derive(Debug, Clone)]
pub struct DeclaredExclusion {
    /// The exclusion entry exactly as written in the CHECKS file.
    pub entry: String,
    /// Config-file-relative paths this exclusion depends on.
    /// An empty vec means the exclusion is never audited (fail-safe).
    pub depends_on: Vec<String>,
}

/// The verdict for a single exclusion re-evaluated as if it were not present.
///
/// Checks must fail safe: when staleness cannot be proven, return `Unknown`
/// rather than `Stale`. A false stale finding trains authors to ignore the check;
/// a missed one merely leaves a dead entry for next time.
#[derive(Debug, Clone)]
pub enum ExclusionStatus {
    /// The exclusion is still required: the target still violates the rule.
    LoadBearing,
    /// The exclusion is no longer required. Contains a short human reason.
    Stale(String),
    /// Staleness could not be determined. Fail-safe default.
    Unknown,
}

/// Declares how much of the repository a check needs to read.
///
/// Returned by `#[check(access_scope = ...)]` and stored in `CheckDescriptor`.
/// `None` in `CheckDescriptor.access_scope` means `modified-only` (the default).
#[derive(Debug, Clone)]
pub enum AccessScope {
    /// Only the files modified in the current changeset (the default).
    ModifiedOnly,
    /// Every file in the repository tree. Explicit opt-in.
    WholeRepo,
    /// Modified files plus files matched by the given repo-root-relative globs.
    Globs(Vec<String>),
    /// The exact required files are declared per-changeset via
    /// `declare_required_files`. The host calls that function before building the
    /// sandbox; the sandbox contains the changeset files plus the returned paths.
    /// No globs — paths must be concrete repo-relative file paths.
    DeclaredFiles,
}

/// Self-description returned by `list-checks`.
#[derive(Debug, Clone)]
pub struct CheckDescriptor {
    pub name: String,
    pub description: String,
    pub default_severity: Severity,
    /// `None` means `modified-only`.
    pub access_scope: Option<AccessScope>,
}

// ── Internal module used by proc-macro expansions ────────────────────────────

/// Not part of the public API. Used only by code generated by `export_checks!`.
#[doc(hidden)]
pub mod __private {
    /// Implemented by each `#[check]`-annotated function's generated companion
    /// struct. Used by `export_checks!` to build the WIT dispatch table.
    pub trait CheckEntry: Send + Sync {
        fn name(&self) -> &'static str;
        fn descriptor(&self) -> crate::CheckDescriptor;
        fn run(&self, input: crate::CheckInput) -> Vec<crate::Finding>;

        /// Compute the fix for this check, returning the edits the host should
        /// apply.
        ///
        /// Populated when the `#[check]` attribute is annotated with
        /// `fix = fn_name`. Defaults to [`crate::FixOutcome::NotFixable`], so a
        /// check without a declared fix is a no-op for `checkleft fix`.
        fn fix(&self, _input: crate::CheckInput) -> crate::FixOutcome {
            crate::FixOutcome::NotFixable
        }

        /// Return the auditable exclusion entries for this check.
        ///
        /// Populated when the `#[check]` attribute is annotated with
        /// `declared_exclusions = fn_name`. Defaults to an empty vec.
        fn declared_exclusions(&self, _config_json: &str) -> Vec<crate::DeclaredExclusion> {
            vec![]
        }

        /// Evaluate whether a previously-declared exclusion is still load-bearing.
        ///
        /// Populated when the `#[check]` attribute is annotated with
        /// `evaluate_exclusion = fn_name`. Defaults to `Unknown`.
        fn evaluate_exclusion(
            &self,
            _config_json: &str,
            _excl: &crate::DeclaredExclusion,
            _file_content: Option<&str>,
        ) -> crate::ExclusionStatus {
            crate::ExclusionStatus::Unknown
        }

        /// Declare the set of additional files needed by this check beyond the
        /// modified-files sandbox.
        ///
        /// Populated when the `#[check]` attribute is annotated with
        /// `required_files = fn_name`. Defaults to an empty vec.
        fn declare_required_files(&self, _changeset: &crate::ChangeSet, _config_json: &str) -> Vec<String> {
            vec![]
        }
    }
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_input() -> CheckInput {
        CheckInput {
            changeset: ChangeSet {
                changed_files: vec![],
                file_diffs: vec![],
                commit_description: None,
                pr_description: None,
                change_id: None,
                repository: None,
                base_files: vec![],
            },
            config_json: "{}".to_owned(),
        }
    }

    #[test]
    fn finding_error_builder() {
        let f = Finding::error("something is wrong");
        assert_eq!(f.severity, Severity::Error);
        assert_eq!(f.message, "something is wrong");
        assert!(f.location.is_none());
        assert!(f.remediations.is_empty());
    }

    #[test]
    fn finding_warning_at() {
        let f = Finding::warning("watch out").at("src/lib.rs", 42);
        let loc = f.location.unwrap();
        assert_eq!(loc.path, "src/lib.rs");
        assert_eq!(loc.line, Some(42));
        assert!(loc.column.is_none());
    }

    #[test]
    fn finding_with_remediation() {
        let f = Finding::info("note").with_remediation("do X").with_remediation("or Y");
        assert_eq!(f.remediations, vec!["do X", "or Y"]);
    }

    #[test]
    fn check_input_config_deserializes_struct() {
        use serde::Deserialize;

        #[derive(Deserialize)]
        struct Cfg {
            threshold: u32,
        }

        let mut input = empty_input();
        input.config_json = r#"{"threshold": 42}"#.to_owned();

        let cfg: Cfg = input.config().unwrap();
        assert_eq!(cfg.threshold, 42);
    }

    #[test]
    fn check_input_config_empty_object() {
        use serde::Deserialize;

        #[derive(Deserialize, Default)]
        struct Cfg {
            #[serde(default)]
            enabled: bool,
        }

        let input = empty_input();
        let cfg: Cfg = input.config().unwrap();
        assert!(!cfg.enabled);
    }

    #[test]
    fn into_fix_outcome_from_vec_is_edits() {
        let edits = vec![FileEdit {
            path: "src/lib.rs".to_owned(),
            old_text: "a".to_owned(),
            new_text: "b".to_owned(),
        }];
        match edits.into_fix_outcome() {
            FixOutcome::Edits(e) => assert_eq!(e.len(), 1),
            other => panic!("expected Edits, got {other:?}"),
        }
    }

    #[test]
    fn into_fix_outcome_from_ok_result_is_edits() {
        let result: Result<Vec<FileEdit>, String> = Ok(vec![]);
        match result.into_fix_outcome() {
            FixOutcome::Edits(e) => assert!(e.is_empty()),
            other => panic!("expected empty Edits, got {other:?}"),
        }
    }

    #[test]
    fn into_fix_outcome_from_err_result_is_failed() {
        let result: Result<Vec<FileEdit>, String> = Err("boom".to_owned());
        match result.into_fix_outcome() {
            FixOutcome::Failed(msg) => assert_eq!(msg, "boom"),
            other => panic!("expected Failed, got {other:?}"),
        }
    }

    #[test]
    fn check_input_config_invalid_json_returns_error() {
        use serde::Deserialize;

        #[derive(Deserialize)]
        #[allow(dead_code)]
        struct Cfg {
            x: u32,
        }

        let mut input = empty_input();
        input.config_json = "not json".to_owned();

        assert!(input.config::<Cfg>().is_err());
    }
}
