//! Reviewer worker: initial-prompt rendering and `ReviewResult` structured
//! output (design §2 and §3 of P992 "Automated reviewer pass on every
//! agent-authored PR").
//!
//! # Role
//!
//! A reviewer worker is a `pr_review` execution dispatched to the dedicated
//! review pool. It operates **read-only**: it reads the PR diff and changed
//! files, produces structured `ReviewResult` JSON, and never writes, commits,
//! pushes, or posts to GitHub. The read-only mandate is enforced at three
//! layers (design §9):
//!
//! 1. **Reviewer CLAUDE.md** — generated by
//!    [`crate::worker_setup::render_claude_md`] when `worker_kind =
//!    WorkerKind::Reviewer`; states the mandate prominently.
//! 2. **Tool denylist** — [`crate::worker_setup::reviewer_deny_rules`],
//!    wired to `WorkerKind::Reviewer` in the settings file.
//! 3. **Prompt mandate** — [`render_reviewer_initial_prompt`] repeats the
//!    read-only constraint in the task prompt alongside the review rubric.
//!
//! # Output contract
//!
//! The reviewer **writes** exactly one `ReviewResult` JSON object to the
//! engine-owned artifact path it is handed (see [`crate::structured_output`]),
//! using the `Write` tool. The completion handler reads + schema-validates
//! that file at the Stop boundary. As a **transitional fallback** (and to keep
//! remote/SSH reviewers working until the artifact is fetched cross-host), the
//! reviewer also ends its final message with the same JSON in a fenced
//! ` ```json ` block, which the legacy [`extract_review_result`] scraper reads
//! when the file is absent. The `ReviewResult` is the sole deliverable; the
//! reviewer must not emit any other action.

use serde::{Deserialize, Serialize};

/// Authoritative PR metadata fetched from GitHub at reviewer-spawn time.
///
/// Pre-fetched before the reviewer worker starts so the reviewer prompt
/// contains the correct base/head SHAs and changed-file list upfront —
/// orientation context the reviewer receives before touching any files.
/// The reviewer workspace is already checked out to the PR head, so file
/// reads go directly against the working tree.
#[derive(Debug, Clone)]
pub struct PrReviewContext {
    /// GitHub PR number (the integer, e.g. `42` for `.../pull/42`).
    pub pr_number: u64,
    /// Full SHA of the base commit the PR is diffed against.
    pub base_sha: String,
    /// Full SHA of the PR's current HEAD commit. The reviewer workspace is
    /// checked out to this SHA, so `Read`/`cat`/`grep` on workspace files
    /// reflect the PR head directly.
    pub head_sha: String,
    /// Paths of every file changed by the PR, relative to the repo root.
    pub changed_files: Vec<String>,
    /// Full output of `gh pr diff` when the diff fits within the configured
    /// line threshold. `None` when the diff was too large to embed or could
    /// not be fetched. When `Some`, the reviewer prompt embeds it directly
    /// so the reviewer skips the `gh pr diff` tool call.
    pub diff_content: Option<String>,
}

/// Which review rubric to apply to a PR.
///
/// The reviewer renders a scope-specific initial prompt so the rubric is
/// always appropriate to the PR's content — the code rubric (correctness,
/// regressions, architecture, tests) does not apply to a pure docs delivery.
///
/// Callers should use [`classify_changed_files`] to derive this from the
/// list of files in the PR diff, falling back to [`ReviewScope::Code`] when
/// the file list is unavailable.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReviewScope {
    /// Standard code PR — apply the full code rubric.
    Code,
    /// Docs-only PR (every changed file is a documentation file) — apply
    /// the light rubric (structure, completeness, required-sections) and
    /// skip the code rubric entirely.
    DocsOnly,
}

/// Classify a list of changed file paths as docs-only or code.
///
/// Returns [`ReviewScope::DocsOnly`] if every path in `files` is a
/// documentation file (`.md`, `.mdx`, `.rst`, `.txt`, or any path that
/// lives under a `docs/` directory at any depth). Returns
/// [`ReviewScope::Code`] if any path is a source, build, or config file,
/// or if `files` is empty (an empty diff defaults to the code rubric).
///
/// # Examples
///
/// ```
/// use boss_engine::pr_review::{classify_changed_files, ReviewScope};
///
/// assert_eq!(
///     classify_changed_files(&["docs/design.md", "README.md"]),
///     ReviewScope::DocsOnly,
/// );
/// assert_eq!(
///     classify_changed_files(&["src/lib.rs", "docs/design.md"]),
///     ReviewScope::Code,
/// );
/// assert_eq!(classify_changed_files(&[]), ReviewScope::Code);
/// ```
pub fn classify_changed_files(files: &[&str]) -> ReviewScope {
    if files.is_empty() {
        return ReviewScope::Code;
    }
    if files.iter().all(|f| is_docs_file(f)) {
        ReviewScope::DocsOnly
    } else {
        ReviewScope::Code
    }
}

fn is_docs_file(path: &str) -> bool {
    let lower = path.to_lowercase();
    lower.ends_with(".md")
        || lower.ends_with(".mdx")
        || lower.ends_with(".rst")
        || lower.ends_with(".txt")
        || lower.starts_with("docs/")
        || lower.contains("/docs/")
}

/// Severity of a review finding — drives the engine's revision-warrant
/// decision (design §3: any `critical`/`high`, or any `regression`,
/// creates a revision regardless of `revision_warranted`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewFindingSeverity {
    Critical,
    High,
    Medium,
    Low,
}

impl ReviewFindingSeverity {
    /// Return the string label used in the prompt schema description.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Critical => "critical",
            Self::High => "high",
            Self::Medium => "medium",
            Self::Low => "low",
        }
    }
}

/// What kind of issue a finding represents.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewFindingCategory {
    /// Logic error, broken invariant, race condition, mishandled error.
    Correctness,
    /// Inadvertent deletion/regression — code dropped that was not the
    /// purpose of the PR (the T793 check class).
    Regression,
    /// Wrong layer, missed reuse, abstraction fights codebase conventions.
    Architecture,
    /// Style, naming, dead/confusing code, fails to match surroundings.
    Readability,
    /// Untested new behaviour, missing edge-case test.
    Tests,
    /// Boundary condition, nullability, concurrency, failure mode.
    #[serde(rename = "edgecase")]
    EdgeCase,
}

/// Reviewer's confidence in a finding.
///
/// `Low` means "suggestion — apply at the revising worker's discretion;
/// this alone does not warrant a revision cycle".
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewFindingConfidence {
    High,
    Medium,
    Low,
}

/// A single actionable review finding.
///
/// Every finding must name a file and state concretely what to change.
/// Vague findings ("consider improving error handling") are not acceptable.
#[derive(Debug, Clone, Serialize, Deserialize, bon::Builder)]
#[builder(on(String, into))]
pub struct ReviewFinding {
    pub severity: ReviewFindingSeverity,
    pub category: ReviewFindingCategory,
    /// File path relative to the repo root.
    pub file: String,
    /// Best-effort location within the file (function name, ~line, hunk).
    /// `None` when the finding applies to the file as a whole.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Short, scannable title (≤ 80 chars).
    pub title: String,
    /// Concrete description of the problem **and** what to change. Must be
    /// specific enough that the revising worker can act without guessing.
    pub detail: String,
    pub confidence: ReviewFindingConfidence,
}

/// First-class regression/deletion check — always present in `ReviewResult`.
///
/// `performed` must be `true`; the reviewer cannot skip the deletion check.
/// If it finds no regressions, it returns `suspected_deletions: []` with
/// `performed: true`.
///
/// `Default` (performed=false, suspected_deletions=[]) exists solely for
/// `#[serde(default)]` on `ReviewResult::regression_check`; it is not a
/// meaningful state for normal use.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct RegressionCheck {
    /// Always `true`. The reviewer must always perform the deletion check.
    pub performed: bool,
    /// All `category = "regression"` findings extracted from `findings`.
    ///
    /// This field is **derived** by [`ReviewResult::from_json`] from
    /// `findings` entries where `category == Regression` and is never read
    /// from the JSON supplied by the reviewer (the reviewer always writes
    /// `suspected_deletions: []`). Skipping deserialization prevents a
    /// type-mismatch serde error when the reviewer fills the field with
    /// descriptive strings instead of `ReviewFinding` objects.
    #[serde(skip_deserializing, default)]
    pub suspected_deletions: Vec<ReviewFinding>,
}

/// Structured output emitted by the reviewer worker in a ```json fenced block
/// in its final message (design §3).
///
/// The engine completion handler extracts this JSON from the final message,
/// parses it, and applies the severity gate to decide whether to create a
/// revision on the producing task. `revision_warranted = false` with no
/// qualifying findings → PR proceeds to human Review unimpeded.
#[derive(Debug, Clone, Serialize, Deserialize, bon::Builder)]
#[builder(on(String, into))]
pub struct ReviewResult {
    /// URL of the PR that was reviewed.
    pub pr_url: String,
    /// HEAD SHA of the PR at review time — used for no-op detection (design
    /// §8) and to guard against racing updates. Best-effort; the engine
    /// tolerates an empty string if `gh pr view` did not supply one.
    pub head_sha: String,
    /// One-paragraph overall assessment of the PR.
    pub summary: String,
    /// Whether the reviewer believes a revision is warranted. The engine
    /// additionally gates on its own severity threshold (any critical/high
    /// or any regression finding forces a revision regardless of this flag).
    pub revision_warranted: bool,
    /// All findings, ordered by severity (critical first, low last).
    pub findings: Vec<ReviewFinding>,
    /// First-class regression/deletion check — always present in well-formed
    /// reviewer output. Defaults to `{performed:false, suspected_deletions:[]}`
    /// if the field is absent or uses a different key (e.g. an older model
    /// using `deletion_check`) so the overall `ReviewResult` can still be
    /// extracted and the `findings`/`revision_warranted` fields honoured.
    #[serde(default)]
    pub regression_check: RegressionCheck,
}

impl ReviewResult {
    /// Parse a `ReviewResult` from a JSON string.
    ///
    /// After deserialization, `regression_check.suspected_deletions` is
    /// populated from `findings` entries where `category == Regression` so
    /// the field is always consistent with `findings` regardless of what the
    /// reviewer wrote in the JSON (the reviewer always emits `suspected_deletions: []`).
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let mut result: Self = serde_json::from_str(json)?;
        result.regression_check.suspected_deletions = result
            .findings
            .iter()
            .filter(|f| matches!(f.category, ReviewFindingCategory::Regression))
            .cloned()
            .collect();
        Ok(result)
    }
}

/// Extract and parse the first `ReviewResult` from a reviewer's final
/// assistant message (design §3 of P992, task 8).
///
/// Tries three strategies in order, returning the first successful parse:
///
/// 1. Fenced ` ```json ` block — the canonical happy-path shape.
/// 2. Plain ` ``` ` block (no language tag).
/// 3. Bare/unfenced JSON — scans for the last balanced `{…}` object in the
///    text and validates it against the `ReviewResult` schema. This handles the
///    observed failure mode where the model emits valid JSON inline after prose
///    without a code fence (e.g. "Key findings below.\n\n{ … }").
///
/// Returns `None` when no parseable `ReviewResult` is found (reviewer may
/// have crashed or emitted malformed output — the caller should fall back to
/// advancing without revision).
///
/// To also receive the serde error from the last failed parse attempt (useful
/// for surfacing in a re-prompt), use [`extract_review_result_verbose`].
pub fn extract_review_result(text: &str) -> Option<ReviewResult> {
    extract_review_result_verbose(text).0
}

/// Like [`extract_review_result`] but also returns the last serde parse error
/// when all strategies fail.
///
/// The error string names the specific field path and type mismatch so the
/// caller can include it verbatim in a reviewer re-prompt, giving the reviewer
/// signal about exactly what is wrong rather than a generic "write valid JSON"
/// message. Returns `(None, None)` when the text contains no JSON-like content
/// at all (the error is only `Some` when a JSON block was present but failed to
/// deserialize as a `ReviewResult`).
pub fn extract_review_result_verbose(text: &str) -> (Option<ReviewResult>, Option<String>) {
    let mut last_error: Option<String> = None;

    // Strategy 1: ```json fenced blocks
    let mut rest = text;
    while let Some(fence_start) = rest.find("```json") {
        let after_fence = &rest[fence_start + 7..];
        let trimmed = after_fence.trim_start_matches('\n');
        if let Some(end) = trimmed.find("```") {
            let json_str = trimmed[..end].trim();
            match ReviewResult::from_json(json_str) {
                Ok(result) => return (Some(result), None),
                Err(e) => last_error = Some(e.to_string()),
            }
        }
        rest = &rest[fence_start + 7..];
    }

    // Strategy 2: plain ``` fenced blocks (no language tag)
    let mut rest = text;
    while let Some(fence_start) = rest.find("```") {
        let after_fence = &rest[fence_start + 3..];
        // Skip if this is actually a ```json or ```jsonc block (already handled)
        let peek = after_fence.trim_start_matches('\n');
        if peek.starts_with("json") {
            rest = &rest[fence_start + 3..];
            continue;
        }
        let trimmed = after_fence.trim_start_matches('\n');
        if let Some(end) = trimmed.find("```") {
            let json_str = trimmed[..end].trim();
            match ReviewResult::from_json(json_str) {
                Ok(result) => return (Some(result), None),
                Err(e) => last_error = Some(e.to_string()),
            }
        }
        rest = &rest[fence_start + 3..];
    }

    // Strategy 3: bare/unfenced JSON — find the last balanced { … } object
    // that validates as a ReviewResult. Scanning from the end handles the
    // common "prose then trailing JSON" shape.
    let bytes = text.as_bytes();
    let mut last_result: Option<ReviewResult> = None;
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'{'
            && let Some(json_str) = extract_balanced_object(&text[i..])
        {
            match ReviewResult::from_json(json_str) {
                Ok(result) => {
                    last_result = Some(result);
                }
                Err(e) => {
                    // Only surface errors from blocks that look like ReviewResults
                    // (contain "revision_warranted") to avoid noise from unrelated
                    // JSON objects in the reviewer's prose.
                    if json_str.contains("revision_warranted") {
                        last_error = Some(e.to_string());
                    }
                }
            }
            // Advance past this object to find any later one
            i += json_str.len();
            continue;
        }
        i += 1;
    }
    if last_result.is_some() {
        return (last_result, None);
    }
    (None, last_error)
}

/// Given a string starting with `{`, return the slice covering the balanced
/// `{…}` object (handling nested braces and string literals). Returns `None`
/// if the input doesn't start with `{` or the braces are unbalanced.
fn extract_balanced_object(s: &str) -> Option<&str> {
    let bytes = s.as_bytes();
    if bytes.first() != Some(&b'{') {
        return None;
    }
    let mut depth: usize = 0;
    let mut in_string = false;
    let mut escape_next = false;
    for (i, &b) in bytes.iter().enumerate() {
        if escape_next {
            escape_next = false;
            continue;
        }
        if in_string {
            match b {
                b'\\' => escape_next = true,
                b'"' => in_string = false,
                _ => {}
            }
        } else {
            match b {
                b'"' => in_string = true,
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        return Some(&s[..=i]);
                    }
                }
                _ => {}
            }
        }
    }
    None
}

/// Engine severity gate (design §3 of P992, task 8).
///
/// Returns `true` when `result` qualifies for a revision:
/// - any finding with `severity = Critical` or `High`, **or**
/// - any finding with `category = Regression` (regardless of severity).
///
/// `revision_warranted = false` in the `ReviewResult` does not suppress the
/// gate — the engine's own threshold governs.
pub fn passes_severity_gate(result: &ReviewResult) -> bool {
    result.findings.iter().any(|f| {
        matches!(
            f.severity,
            ReviewFindingSeverity::Critical | ReviewFindingSeverity::High
        ) || matches!(f.category, ReviewFindingCategory::Regression)
    })
}

/// Render qualifying `ReviewResult` findings as human-readable revision
/// instructions (design §4 of P992, task 8).
///
/// Groups all findings by severity (critical first, low last) and formats
/// each with its title, file, location, and concrete detail. The rendering
/// is the `revision_instructions` passed to the revising worker — it must
/// be specific enough to act on without guessing.
pub fn render_revision_instructions(result: &ReviewResult) -> String {
    let severity_rank = |s: &ReviewFindingSeverity| match s {
        ReviewFindingSeverity::Critical => 0u8,
        ReviewFindingSeverity::High => 1,
        ReviewFindingSeverity::Medium => 2,
        ReviewFindingSeverity::Low => 3,
    };

    let mut findings = result.findings.clone();
    findings.sort_by_key(|f| severity_rank(&f.severity));

    let mut out = format!(
        "Automated PR review found {} finding(s) requiring attention.\n\
         Address all findings before finalising this revision.\n\n",
        findings.len()
    );

    for f in &findings {
        let loc = f.location.as_deref().map(|l| format!(" ({l})")).unwrap_or_default();
        let category = match f.category {
            ReviewFindingCategory::Correctness => "correctness",
            ReviewFindingCategory::Regression => "regression",
            ReviewFindingCategory::Architecture => "architecture",
            ReviewFindingCategory::Readability => "readability",
            ReviewFindingCategory::Tests => "tests",
            ReviewFindingCategory::EdgeCase => "edgecase",
        };
        out.push_str(&format!(
            "### [{severity}] {title}\n\
             **File:** `{file}`{loc}  \n\
             **Category:** {category}  \n\
             **Confidence:** {confidence}\n\n\
             {detail}\n\n",
            severity = f.severity.as_str(),
            title = f.title,
            file = f.file,
            category = category,
            confidence = match f.confidence {
                ReviewFindingConfidence::High => "high",
                ReviewFindingConfidence::Medium => "medium",
                ReviewFindingConfidence::Low => "low",
            },
            detail = f.detail,
        ));
    }

    out.push_str(&format!("**Review summary:** {}\n", result.summary));
    out
}

/// Render the CLAUDE.md for a reviewer worker (design §9 of P992).
///
/// Reviewer workers operate **read-only**: they read PR diffs and workspace
/// files but must not write, push, or post to GitHub. This CLAUDE.md
/// prominently states that mandate and omits PR-creation / VCS-push
/// guidance entirely (those actions are also blocked by the reviewer denylist,
/// so this is the belt that accompanies that suspenders layer).
///
/// The workspace is already checked out to the PR head SHA, so the reviewer
/// can read files directly without `gh pr diff` for every lookup.
pub fn render_reviewer_claude_md(lease_id: &str, workspace_path: &str) -> String {
    format!(
        "# Boss reviewer rules\n\
         \n\
         You are running inside a Boss-managed **reviewer** session. The engine\n\
         spawned you in a leased cube workspace checked out to the PR head.\n\
         \n\
         ## Read-only mandate (HARD CONSTRAINT)\n\
         \n\
         **You MUST NOT change the PR or its branch in any way.**\n\
         \n\
         Forbidden actions (tool calls for these are denied):\n\
         \n\
         - Editing any file, or writing any file inside this workspace or any\n\
           sibling worker workspace (`Edit`, `Write` under the workspaces root).\n\
         - Committing or pushing (`jj git push`, `git push`).\n\
         - Opening, merging, closing, editing, or commenting on a PR\n\
           (`gh pr create/merge/close/edit/comment/review`).\n\
         - Interacting with GitHub issues in any write capacity.\n\
         - Running `cube pr ensure` or any Boss PR helper.\n\
         \n\
         **The one permitted write** is your `ReviewResult` JSON, which you\n\
         write with the `Write` tool to the engine-owned artifact path given in\n\
         your task prompt (also exported as `$BOSS_STRUCTURED_OUTPUT`). That\n\
         path is OUTSIDE every worker workspace, so it is not part of the PR or\n\
         repo — writing it does not violate the read-only mandate. Do not write\n\
         anywhere else.\n\
         \n\
         Anything you would \"fix\", describe as a finding in the\n\
         `ReviewResult` JSON instead. Your feedback stays inside Boss —\n\
         **it is never posted to GitHub**.\n\
         \n\
         Allowed read-only tools: `grep`, `find`, `cat`, `head`, `tail`,\n\
         `Read`, `jj log`, `jj show`, `jj diff`, `gh pr view`, `gh pr diff`,\n\
         `gh pr list`, and similar read-only operations.\n\
         \n\
         ## Your workspace\n\
         \n\
         - Workspace path: `{workspace_path}`\n\
         - Cube lease id: `{lease}`\n\
         \n\
         The workspace is already checked out to the PR head. You can read\n\
         changed files and surrounding context directly — use `Read`, `cat`,\n\
         `grep`, etc. on files in `{workspace_path}`. No need to use\n\
         `git show <sha>:<path>` or fetch files via `gh`.\n\
         \n\
         Lease held for the lifetime of this run. Do not lease, release,\n\
         or mutate cube state.\n\
         \n\
         ## VCS (read-only)\n\
         \n\
         Use `jj` for read-only navigation. Do not push or modify history.\n\
         \n\
         - `jj log`, `jj show`, `jj diff` — browse history and diffs.\n\
         - `gh pr diff <url>` — fetch the PR diff (useful for the annotated diff view).\n\
         - `gh pr view <url>` — read the PR description.\n\
         \n\
         ## Boundaries\n\
         \n\
         - Do not modify files outside your workspace. Other workspaces\n\
           belong to other workers.\n\
         - Do not modify cube's database, lease state, or workspace registry.\n\
         - `~/Library/Application Support/Boss/` is coordinator/engine-only.\n\
           Never read, write, or touch it.\n\
           `bossctl` is coordinator-only.\n\
         \n\
         ## Coordinator\n\
         \n\
         The coordinator may probe this session between turns. Treat probes\n\
         as questions from a human reviewer — short, specific answers.\n",
        lease = lease_id,
        workspace_path = workspace_path,
    )
}

/// Compose the initial-prompt for a `pr_review` execution (design §2, §12).
///
/// `task_name` and `task_description` are the producing task's title and
/// description — they tell the reviewer what the PR was *supposed* to do,
/// which is the baseline for the regression/deletion check.
///
/// `pr_url` is the PR to review.
///
/// `scope` controls which rubric is rendered:
/// - [`ReviewScope::Code`] — the full code rubric (correctness, regressions,
///   architecture, tests, edge cases), plus a fallback note to switch to the
///   docs rubric if all changed files turn out to be documentation files.
/// - [`ReviewScope::DocsOnly`] — only the light docs rubric (structure,
///   completeness, required-sections). The code rubric is omitted entirely.
///
/// `ctx` is the pre-fetched PR metadata. When `Some`, the prompt embeds the
/// base/head SHAs and changed-file list as orientation context. When `None`
/// (fetch failed), the prompt falls back to URL-only framing. In both cases
/// the reviewer workspace is at the PR head and can read files directly.
///
/// When the engine cannot pre-classify the PR (no file list available),
/// pass [`ReviewScope::Code`]; the self-detection fallback in the code rubric
/// section covers that case.
///
/// `output_path` is the absolute, engine-owned artifact path the reviewer must
/// write its `ReviewResult` JSON to (see [`crate::structured_output`]). It is
/// the primary output channel; the prompt also asks for a fenced-JSON copy in
/// the final message as a transitional fallback.
pub fn render_reviewer_initial_prompt(
    task_name: &str,
    task_description: &str,
    pr_url: &str,
    output_path: &str,
    scope: ReviewScope,
    ctx: Option<&PrReviewContext>,
) -> String {
    let rubric = render_rubric_section(&scope);

    // Extended PR metadata block — only present when we have pre-fetched context.
    let pr_metadata_block = match ctx {
        Some(ctx) => {
            let files = if ctx.changed_files.is_empty() {
                "*(unavailable)*".to_owned()
            } else {
                ctx.changed_files
                    .iter()
                    .map(|f| format!("- `{f}`"))
                    .collect::<Vec<_>>()
                    .join("\n")
            };
            format!(
                "**Base commit:** `{base}`  \n\
                 **Head commit:** `{head}`  \n\
                 **Changed files ({n}):**\n\
                 {files}\n",
                base = ctx.base_sha,
                head = ctx.head_sha,
                n = ctx.changed_files.len(),
                files = files,
            )
        }
        None => String::new(),
    };

    // Short reference for `gh` commands — PR number is cleaner than the full
    // URL and avoids `gh` having to parse it, but fall back to URL when the
    // number is unavailable.
    let pr_ref = ctx
        .map(|c| c.pr_number.to_string())
        .unwrap_or_else(|| pr_url.to_owned());

    // Head SHA for the ReviewResult schema example — use the known SHA when
    // available so the reviewer can copy it directly rather than fetching it.
    let schema_head_sha = ctx
        .map(|c| c.head_sha.as_str())
        .unwrap_or("<sha from gh pr view --json headRefOid>");

    // When the diff is small enough, embed it directly so the reviewer
    // doesn't need a `gh pr diff` tool call.
    let embedded_diff = ctx.and_then(|c| c.diff_content.as_deref());
    let diff_step = if embedded_diff.is_some() {
        "2. The PR diff is pre-embedded in the **Embedded diff** section \
         below — no need to fetch it separately.\n"
            .to_owned()
    } else {
        format!("2. Get the diff for the annotated view: `gh pr diff {pr_ref}`\n")
    };
    let embedded_diff_section = match embedded_diff {
        Some(diff) => format!(
            "## Embedded diff\n\
             \n\
             Pre-fetched at review time. Read it carefully before forming \
             findings.\n\
             \n\
             ```diff\n\
             {diff}\n\
             ```\n\
             \n"
        ),
        None => String::new(),
    };

    format!(
        "# PR review\n\
         \n\
         You are an independent PR reviewer. Your ONLY job is to review the \
         PR and produce a single structured `ReviewResult` JSON. You MUST NOT \
         change the PR in any way: no commits, no pushes, no `gh` writes, no \
         edits to repo files or branches, no comments on GitHub. You operate \
         **read-only** on the PR. The ONE write you make is your `ReviewResult` \
         JSON, to the engine-owned artifact path below (outside the repo). \
         Anything you would \"fix\" you instead describe as a \
         finding. Posting to GitHub is prohibited — your feedback stays inside \
         Boss as an internal revision.\n\
         \n\
         ## PR under review\n\
         \n\
         **Task:** {task_name}\n\
         \n\
         **Task description:**\n\
         {task_description}\n\
         \n\
         **PR:** {pr_url}\n\
         {pr_metadata_block}\n\
         ## Review steps\n\
         \n\
         1. Your workspace is already checked out to the PR head — read \
            changed files directly with `Read`, `cat`, `grep`, etc.\n\
         {diff_step}\
         3. Get the PR description: `gh pr view {pr_ref}`\n\
         4. Read changed files and surrounding context using `Read`, `cat`, \
            `grep`, `jj show`, etc. — no writes to repo files.\n\
         5. Produce the `ReviewResult` JSON (schema below) and deliver it as \
            described in **Required output** — write it to the artifact file \
            with the `Write` tool, and also include it as a fenced \
            ` ```json ` block at the end of your final message.\n\
         \n\
         {embedded_diff_section}\
         {rubric}\n\
         ## Speed/comprehensiveness balance\n\
         \n\
         Prefer **fast, high-signal feedback** over exhaustive analysis. \
         Every PR may now pass through up to ~3 produce→review→revise cycles, \
         so do NOT excessively lengthen turnaround. Spend your scrutiny budget \
         on correctness and regressions first. If in doubt about a \
         non-critical suggestion, you MAY offer it WITHOUT deep analysis \
         and mark it `low` severity and `low` confidence — the revising \
         worker decides whether to apply it.\n\
         \n\
         ## Required output — CRITICAL\n\
         \n\
         **Primary (required):** write your single `ReviewResult` JSON object \
         to this exact file using the `Write` tool — nothing else, just the \
         JSON:\n\
         \n\
         `{output_path}`\n\
         \n\
         This path is also exported as `$BOSS_STRUCTURED_OUTPUT`. It lives \
         outside every repo/workspace, so writing it is the one write you are \
         permitted (it does not touch the PR). The engine reads and \
         schema-validates this file; if it is missing or invalid the engine \
         will ask you to write it again.\n\
         \n\
         **Also (fallback):** end your final message with the same \
         `ReviewResult` JSON in a fenced ` ```json ` block as the LAST content \
         in your message — nothing follows the closing ` ``` `. This is a \
         backstop the engine uses only if the file is unreadable. No other \
         terminal action is permitted.\n\
         \n\
         Schema:\n\
         \n\
         ```jsonc\n\
         {{\n\
           \"pr_url\": \"{pr_url}\",\n\
           \"head_sha\": \"{schema_head_sha}\",\n\
           \"summary\": \"<one-paragraph overall assessment>\",\n\
           \"revision_warranted\": true,\n\
           \"findings\": [\n\
             {{\n\
               \"severity\": \"critical | high | medium | low\",\n\
               \"category\": \"correctness | regression | architecture | readability | tests | edgecase\",\n\
               \"file\": \"path/to/file.rs\",\n\
               \"location\": \"fn foo, ~L42\",\n\
               \"title\": \"<short scannable title>\",\n\
               \"detail\": \"<concrete description + what to change>\",\n\
               \"confidence\": \"high | medium | low\"\n\
             }}\n\
           ],\n\
           \"regression_check\": {{\n\
             \"performed\": true,\n\
             \"suspected_deletions\": []\n\
           }}\n\
         }}\n\
         ```\n\
         \n\
         Rules:\n\
         \n\
         - `revision_warranted`: set to `true` when there is at least one \
           finding at `critical`/`high` severity, or any finding with \
           `category: \"regression\"`, regardless of severity. Set to `false` \
           for findings that are purely `medium`/`low` correctness/style \
           (the engine applies its own gate on top).\n\
         - `regression_check.performed` MUST be `true` — you cannot skip the \
           deletion check. Always set `suspected_deletions: []`; regression \
           findings go in `findings` with `category: \"regression\"` and the \
           engine derives this list automatically — do NOT populate it.\n\
         - `findings` may be empty if the PR is clean. `revision_warranted` \
           must then be `false`.\n\
         - `location` is optional (omit the key if the finding applies to the \
           whole file).\n\
         - Do NOT post this JSON to GitHub or as a PR comment. It stays \
           inside Boss.\n",
        task_name = task_name,
        task_description = task_description,
        pr_url = pr_url,
        output_path = output_path,
        pr_metadata_block = pr_metadata_block,
        pr_ref = pr_ref,
        diff_step = diff_step,
        embedded_diff_section = embedded_diff_section,
        schema_head_sha = schema_head_sha,
        rubric = rubric,
    )
}

fn render_rubric_section(scope: &ReviewScope) -> String {
    match scope {
        ReviewScope::Code => "## Review rubric — code PR\n\
             \n\
             Apply a **high bar**: push back only on real problems, not \
             stylistic preferences. Every finding must name a file (and \
             function/line/hunk where possible) and state **concretely what to \
             change**. Vague findings are not acceptable.\n\
             \n\
             Review for:\n\
             \n\
             - **Critical correctness** — logic errors, broken invariants, \
               mishandled errors, race conditions. (`category: \"correctness\"`)\n\
             - **Inadvertent regressions** *(first-class, explicit check)* — \
               diff against `main` and flag anything dropped that is unrelated \
               to the PR's stated purpose. Conflict-resolution and forward-port \
               PRs get extra scrutiny here. This is the T793 check: a live \
               feature silently removed during a forward-port must be caught. \
               (`category: \"regression\"`)\n\
             - **Architectural issues** — wrong layer, missed reuse, abstraction \
               that fights the codebase's conventions. (`category: \
               \"architecture\"`)\n\
             - **Code quality/readability** — fails to match surrounding style, \
               naming issues, dead/confusing code. (`category: \"readability\"`)\n\
             - **Test coverage gaps** — untested new behaviour, missing \
               edge-case tests. (`category: \"tests\"`)\n\
             - **Edge cases/gotchas** — boundary conditions, nullability, \
               concurrency, failure modes. (`category: \"edgecase\"`)\n\
             \n\
             **Docs-only fallback:** if you determine that every changed file \
             is a documentation file (`.md`, `.mdx`, `.rst`, design docs, \
             READMEs) with no source-code changes, switch to the light docs \
             rubric below and skip the code rubric above.\n\
             \n\
             - Structure and completeness of the document.\n\
             - Internal consistency (no contradictions within the doc).\n\
             - Required-sections check for design docs (problem/goals/approach \
               headings present).\n\
             \n"
        .to_owned(),
        ReviewScope::DocsOnly => "## Review rubric — docs-only PR\n\
             \n\
             This PR contains only documentation files. Apply the **light \
             rubric** — skip code-review concerns (correctness, regressions, \
             architecture, tests) entirely.\n\
             \n\
             Review for:\n\
             \n\
             - **Structure and completeness** — is the document well-organised \
               and does it cover what it claims to cover?\n\
             - **Internal consistency** — no contradictions within the doc; \
               claims made in one section are consistent with claims in another.\n\
             - **Required-sections check** — for design docs, verify that the \
               expected headings are present: Problem / Goal, Goals, Chosen \
               approach (or equivalent). Flag any that are absent or \
               substantively empty.\n\
             \n\
             Do NOT apply the code rubric (correctness, regressions, \
             architecture, tests, edge cases) to this docs-only PR.\n\
             \n"
        .to_owned(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn review_result_roundtrips_through_json() {
        let result = ReviewResult {
            pr_url: "https://github.com/org/repo/pull/42".to_owned(),
            head_sha: "abc123def456".to_owned(),
            summary: "Overall the PR looks good with one regression.".to_owned(),
            revision_warranted: true,
            findings: vec![ReviewFinding {
                severity: ReviewFindingSeverity::High,
                category: ReviewFindingCategory::Regression,
                file: "tools/boss/engine/src/lib.rs".to_owned(),
                location: Some("fn init, ~L10".to_owned()),
                title: "Forward-port dropped the autostart feature".to_owned(),
                detail: "The autostart flag was removed in the conflict resolution; \
                         restore it."
                    .to_owned(),
                confidence: ReviewFindingConfidence::High,
            }],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        let json = serde_json::to_string(&result).expect("serializes");
        let parsed = ReviewResult::from_json(&json).expect("deserializes");
        assert_eq!(parsed.pr_url, result.pr_url);
        assert_eq!(parsed.head_sha, result.head_sha);
        assert!(parsed.revision_warranted);
        assert_eq!(parsed.findings.len(), 1);
        assert_eq!(parsed.findings[0].severity, ReviewFindingSeverity::High);
        assert_eq!(parsed.findings[0].category, ReviewFindingCategory::Regression);
        assert!(parsed.regression_check.performed);
    }

    #[test]
    fn review_result_empty_findings_deserializes() {
        let json = serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/7",
            "head_sha": "",
            "summary": "LGTM, no issues found.",
            "revision_warranted": false,
            "findings": [],
            "regression_check": {
                "performed": true,
                "suspected_deletions": []
            }
        });
        let result = ReviewResult::from_json(&json.to_string()).expect("deserializes");
        assert!(!result.revision_warranted);
        assert!(result.findings.is_empty());
        assert!(result.regression_check.performed);
    }

    #[test]
    fn reviewer_initial_prompt_contains_rubric_and_pr_url() {
        let prompt = render_reviewer_initial_prompt(
            "Fix the auth bug",
            "Auth middleware drops sessions on timeout.",
            "https://github.com/org/repo/pull/99",
            "/tmp/bwo/exec.json",
            ReviewScope::Code,
            None,
        );
        assert!(prompt.contains("https://github.com/org/repo/pull/99"));
        assert!(prompt.contains("Fix the auth bug"));
        assert!(prompt.contains("Auth middleware drops sessions on timeout."));
        assert!(prompt.contains("regression"));
        assert!(prompt.contains("correctness"));
        assert!(prompt.contains("revision_warranted"));
        assert!(prompt.contains("regression_check"));
        assert!(prompt.contains("read-only"));
        assert!(prompt.contains("gh pr diff"));
    }

    #[test]
    fn reviewer_initial_prompt_states_workspace_at_pr_head() {
        let prompt = render_reviewer_initial_prompt(
            "Fix the auth bug",
            "Auth middleware drops sessions on timeout.",
            "https://github.com/org/repo/pull/99",
            "/tmp/bwo/exec.json",
            ReviewScope::Code,
            None,
        );
        assert!(
            prompt.contains("already checked out to the PR head"),
            "prompt must state workspace is at PR head"
        );
        assert!(
            !prompt.contains("DO THIS FIRST"),
            "prompt must not have defensive 'do this first' emphasis"
        );
        assert!(
            !prompt.contains("git show"),
            "prompt must not instruct anchoring reads via git show"
        );
    }

    #[test]
    fn reviewer_initial_prompt_with_context_embeds_metadata() {
        let ctx = PrReviewContext {
            pr_number: 99,
            base_sha: "base000".to_owned(),
            head_sha: "head999".to_owned(),
            changed_files: vec!["src/main.rs".to_owned(), "tests/test.rs".to_owned()],
            diff_content: None,
        };
        let prompt = render_reviewer_initial_prompt(
            "Fix the auth bug",
            "Auth middleware drops sessions on timeout.",
            "https://github.com/org/repo/pull/99",
            "/tmp/bwo/exec.json",
            ReviewScope::Code,
            Some(&ctx),
        );
        assert!(prompt.contains("base000"), "prompt must include base SHA");
        assert!(prompt.contains("head999"), "prompt must include head SHA");
        assert!(prompt.contains("src/main.rs"), "prompt must list changed files");
        assert!(prompt.contains("tests/test.rs"), "prompt must list changed files");
        assert!(
            prompt.contains("gh pr diff 99"),
            "prompt must use PR number in diff command"
        );
        assert!(
            prompt.contains("already checked out to the PR head"),
            "prompt must state workspace is at PR head"
        );
        assert!(
            !prompt.contains("git show head999:"),
            "prompt must not instruct reads via git show"
        );
        assert!(
            !prompt.contains("NOT at the PR head"),
            "prompt must not warn that working tree is stale"
        );
    }

    #[test]
    fn reviewer_initial_prompt_with_embedded_diff_omits_gh_pr_diff_step() {
        let ctx = PrReviewContext {
            pr_number: 42,
            base_sha: "base111".to_owned(),
            head_sha: "head222".to_owned(),
            changed_files: vec!["src/lib.rs".to_owned()],
            diff_content: Some("diff --git a/src/lib.rs b/src/lib.rs\n+fn new() {}".to_owned()),
        };
        let prompt = render_reviewer_initial_prompt(
            "Add a feature",
            "Implement the new feature.",
            "https://github.com/org/repo/pull/42",
            "/tmp/bwo/exec.json",
            ReviewScope::Code,
            Some(&ctx),
        );
        assert!(
            !prompt.contains("gh pr diff 42"),
            "prompt must NOT instruct reviewer to call gh pr diff when diff is embedded"
        );
        assert!(
            prompt.contains("Embedded diff"),
            "prompt must include the embedded diff section"
        );
        assert!(
            prompt.contains("diff --git a/src/lib.rs"),
            "prompt must contain the actual diff content"
        );
        assert!(
            prompt.contains("no need to fetch it separately"),
            "prompt must tell reviewer not to fetch the diff"
        );
    }

    #[test]
    fn reviewer_initial_prompt_without_diff_content_uses_gh_pr_diff_step() {
        let ctx = PrReviewContext {
            pr_number: 42,
            base_sha: "base111".to_owned(),
            head_sha: "head222".to_owned(),
            changed_files: vec!["src/lib.rs".to_owned()],
            diff_content: None,
        };
        let prompt = render_reviewer_initial_prompt(
            "Add a feature",
            "Implement the new feature.",
            "https://github.com/org/repo/pull/42",
            "/tmp/bwo/exec.json",
            ReviewScope::Code,
            Some(&ctx),
        );
        assert!(
            prompt.contains("gh pr diff 42"),
            "prompt must instruct reviewer to call gh pr diff when no diff is embedded"
        );
        assert!(
            !prompt.contains("Embedded diff"),
            "prompt must NOT include the embedded diff section when diff_content is None"
        );
    }

    #[test]
    fn code_scope_prompt_contains_code_rubric_and_docs_fallback() {
        let prompt = render_reviewer_initial_prompt(
            "Fix the auth bug",
            "Auth middleware drops sessions on timeout.",
            "https://github.com/org/repo/pull/99",
            "/tmp/bwo/exec.json",
            ReviewScope::Code,
            None,
        );
        assert!(prompt.contains("code PR"));
        assert!(prompt.contains("Docs-only fallback"));
        assert!(prompt.contains("light docs rubric"));
        // Code rubric categories must be present.
        assert!(prompt.contains("correctness"));
        assert!(prompt.contains("regressions"));
        assert!(prompt.contains("architecture"));
        assert!(prompt.contains("tests"));
    }

    #[test]
    fn docs_only_scope_prompt_contains_docs_rubric_and_no_code_rubric() {
        let prompt = render_reviewer_initial_prompt(
            "Add design doc",
            "Write a design doc for feature X.",
            "https://github.com/org/repo/pull/100",
            "/tmp/bwo/exec.json",
            ReviewScope::DocsOnly,
            None,
        );
        assert!(prompt.contains("docs-only PR"));
        assert!(prompt.contains("light rubric"));
        assert!(prompt.contains("Internal consistency"));
        assert!(prompt.contains("Required-sections check"));
        // Code rubric must NOT appear in docs-only prompt.
        assert!(!prompt.contains("code PR"));
        assert!(!prompt.contains("T793"));
    }

    #[test]
    fn reviewer_initial_prompt_states_speed_balance() {
        let prompt = render_reviewer_initial_prompt(
            "T",
            "D",
            "https://github.com/pr/1",
            "/tmp/bwo/exec.json",
            ReviewScope::Code,
            None,
        );
        assert!(prompt.contains("fast, high-signal"));
        assert!(prompt.contains("scrutiny budget"));
    }

    #[test]
    fn reviewer_initial_prompt_directs_write_to_artifact_path() {
        let prompt = render_reviewer_initial_prompt(
            "T",
            "D",
            "https://github.com/pr/1",
            "/var/tmp/boss-worker-output/exec_abc_1.json",
            ReviewScope::Code,
            None,
        );
        // The artifact path is embedded verbatim as the primary output target.
        assert!(
            prompt.contains("/var/tmp/boss-worker-output/exec_abc_1.json"),
            "prompt must embed the literal artifact path"
        );
        assert!(
            prompt.contains("$BOSS_STRUCTURED_OUTPUT"),
            "prompt must reference the env var fallback"
        );
        assert!(
            prompt.contains("`Write` tool"),
            "prompt must instruct using the Write tool"
        );
        // Fenced JSON is kept as a transitional fallback, not the primary.
        assert!(
            prompt.contains("fallback"),
            "prompt must describe the fenced-JSON fallback"
        );
    }

    // --- classify_changed_files ---

    #[test]
    fn classify_empty_files_returns_code() {
        assert_eq!(classify_changed_files(&[]), ReviewScope::Code);
    }

    #[test]
    fn classify_all_md_files_returns_docs_only() {
        assert_eq!(
            classify_changed_files(&["README.md", "docs/design.md", "CHANGELOG.md"]),
            ReviewScope::DocsOnly,
        );
    }

    #[test]
    fn classify_mixed_returns_code() {
        assert_eq!(classify_changed_files(&["README.md", "src/lib.rs"]), ReviewScope::Code,);
    }

    #[test]
    fn classify_mdx_and_rst_count_as_docs() {
        assert_eq!(
            classify_changed_files(&["docs/guide.mdx", "notes.rst"]),
            ReviewScope::DocsOnly,
        );
    }

    #[test]
    fn classify_docs_dir_prefix_counts_as_docs() {
        assert_eq!(
            classify_changed_files(&["docs/architecture/overview.txt"]),
            ReviewScope::DocsOnly,
        );
    }

    #[test]
    fn classify_docs_subdir_in_path_counts_as_docs() {
        assert_eq!(
            classify_changed_files(&["tools/boss/docs/designs/foo.md"]),
            ReviewScope::DocsOnly,
        );
    }

    #[test]
    fn classify_rs_file_alone_returns_code() {
        assert_eq!(
            classify_changed_files(&["tools/boss/engine/src/lib.rs"]),
            ReviewScope::Code,
        );
    }

    #[test]
    fn classify_build_file_with_docs_returns_code() {
        assert_eq!(
            classify_changed_files(&["docs/guide.md", "BUILD.bazel"]),
            ReviewScope::Code,
        );
    }

    #[test]
    fn review_finding_severity_roundtrips_as_snake_case() {
        for (sev, expected) in [
            (ReviewFindingSeverity::Critical, "\"critical\""),
            (ReviewFindingSeverity::High, "\"high\""),
            (ReviewFindingSeverity::Medium, "\"medium\""),
            (ReviewFindingSeverity::Low, "\"low\""),
        ] {
            let json = serde_json::to_string(&sev).unwrap();
            assert_eq!(json, expected);
            let back: ReviewFindingSeverity = serde_json::from_str(&json).unwrap();
            assert_eq!(back, sev);
        }
    }

    #[test]
    fn review_finding_category_roundtrips_as_snake_case() {
        for (cat, expected) in [
            (ReviewFindingCategory::Correctness, "\"correctness\""),
            (ReviewFindingCategory::Regression, "\"regression\""),
            (ReviewFindingCategory::Architecture, "\"architecture\""),
            (ReviewFindingCategory::Readability, "\"readability\""),
            (ReviewFindingCategory::Tests, "\"tests\""),
            (ReviewFindingCategory::EdgeCase, "\"edgecase\""),
        ] {
            let json = serde_json::to_string(&cat).unwrap();
            assert_eq!(json, expected);
            let back: ReviewFindingCategory = serde_json::from_str(&json).unwrap();
            assert_eq!(back, cat);
        }
    }

    /// A `ReviewResult` that omits `regression_check` entirely (e.g., a model
    /// that used the old `deletion_check` key) must still parse successfully.
    /// The `findings`/`revision_warranted` fields carry all the information the
    /// engine needs; silently discarding the whole review for a missing optional
    /// field is the T1359 failure mode.
    #[test]
    fn review_result_parses_without_regression_check_field() {
        let json = serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/1",
            "head_sha": "abc",
            "summary": "Found a bug.",
            "revision_warranted": true,
            "findings": [
                {
                    "severity": "high",
                    "category": "correctness",
                    "file": "src/lib.rs",
                    "title": "Orphan tag leak",
                    "detail": "The tag is created before the push check.",
                    "confidence": "high"
                }
            ]
            // regression_check intentionally omitted — T1359 failure mode
        });
        let result = ReviewResult::from_json(&json.to_string())
            .expect("ReviewResult must parse even without regression_check (T1359 robustness)");
        assert!(result.revision_warranted, "revision_warranted must be preserved");
        assert_eq!(result.findings.len(), 1, "findings must be preserved");
        assert!(
            !result.regression_check.performed,
            "missing regression_check defaults to performed=false"
        );
    }

    #[test]
    fn regression_check_performed_must_be_true_in_valid_result() {
        let json = serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/1",
            "head_sha": "abc",
            "summary": "ok",
            "revision_warranted": false,
            "findings": [],
            "regression_check": {
                "performed": true,
                "suspected_deletions": []
            }
        });
        let result = ReviewResult::from_json(&json.to_string()).unwrap();
        assert!(result.regression_check.performed);
    }

    // --- extract_review_result ---

    fn make_review_result_json(revision_warranted: bool, findings: serde_json::Value) -> String {
        serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/1",
            "head_sha": "abc",
            "summary": "summary text",
            "revision_warranted": revision_warranted,
            "findings": findings,
            "regression_check": { "performed": true, "suspected_deletions": [] }
        })
        .to_string()
    }

    #[test]
    fn extract_review_result_parses_fenced_json_block() {
        let json = make_review_result_json(false, serde_json::json!([]));
        let text = format!("Here is my review:\n\n```json\n{json}\n```\n\nDone.");
        let result = extract_review_result(&text).expect("should parse");
        assert_eq!(result.pr_url, "https://github.com/org/repo/pull/1");
        assert!(!result.revision_warranted);
    }

    #[test]
    fn extract_review_result_returns_none_for_plain_text() {
        let text = "No structured output here, just prose.";
        assert!(extract_review_result(text).is_none());
    }

    #[test]
    fn extract_review_result_returns_none_for_malformed_json() {
        let text = "```json\n{ not valid json }\n```";
        assert!(extract_review_result(text).is_none());
    }

    #[test]
    fn extract_review_result_finds_block_after_prose() {
        let json = make_review_result_json(true, serde_json::json!([]));
        let text = format!("I reviewed the PR.\n\nSome analysis here.\n\n```json\n{json}\n```");
        let result = extract_review_result(&text).expect("should parse");
        assert!(result.revision_warranted);
    }

    #[test]
    fn extract_review_result_parses_plain_fenced_block() {
        let json = make_review_result_json(false, serde_json::json!([]));
        let text = format!("Here is the result:\n\n```\n{json}\n```\n");
        let result = extract_review_result(&text).expect("should parse plain fence");
        assert_eq!(result.pr_url, "https://github.com/org/repo/pull/1");
    }

    #[test]
    fn extract_review_result_parses_bare_json_after_prose() {
        // Regression fixture for T1304 / PR #1320 shape:
        // "## Review summary … Key findings below.\n\n{ … }"
        let json = make_review_result_json(
            true,
            serde_json::json!([
                {
                    "severity": "high",
                    "category": "correctness",
                    "file": "src/lib.rs",
                    "title": "missing null check",
                    "detail": "foo can be null here",
                    "confidence": "high"
                }
            ]),
        );
        let text = format!(
            "## Review summary\n\nI reviewed the PR carefully.\n\
             \nKey findings below.\n\n{json}"
        );
        let result = extract_review_result(&text).expect("should parse bare JSON after prose");
        assert!(result.revision_warranted);
        assert_eq!(result.findings.len(), 1);
    }

    #[test]
    fn extract_review_result_parses_trailing_bare_json() {
        let json = make_review_result_json(false, serde_json::json!([]));
        let text = format!("Some prose up front.\n\n{json}");
        let result = extract_review_result(&text).expect("should parse trailing bare JSON");
        assert!(!result.revision_warranted);
    }

    #[test]
    fn extract_review_result_prefers_last_valid_result_in_bare_scan() {
        // If there are multiple JSON-like objects, the last valid ReviewResult wins.
        let json1 = make_review_result_json(false, serde_json::json!([]));
        let json2 = make_review_result_json(true, serde_json::json!([]));
        let text = format!("First: {json1}\n\nSecond: {json2}");
        let result = extract_review_result(&text).expect("should parse");
        assert!(result.revision_warranted, "should use the last valid result");
    }

    #[test]
    fn extract_review_result_ignores_non_review_result_json_objects() {
        let text = r#"Some context {"key": "value", "unrelated": true} then prose."#;
        assert!(extract_review_result(text).is_none());
    }

    /// Regression test for T1359 — the EXACT quark ReviewResult JSON that was
    /// silently dropped by `extract_review_result` in boss-v1.0.88 (exec
    /// `exec_18b5da2a31922490_161`). The JSON is fed BARE (no ` ```json ` fence)
    /// exactly as the reviewer emitted it. If this test fails the T1359 failure
    /// mode is still live; if it passes the parser handles this specific input.
    ///
    /// Key diagnostic targets:
    /// (a) `extract_balanced_object` mis-bounding on `\"${NOTES_FILE}\"` in
    ///     finding[2].detail (escaped quotes + `${...}` inside a string literal).
    /// (b) `ReviewResult` serde rejecting a present field such as `regression_check`.
    #[test]
    fn extract_review_result_t1359_exact_quark_json_bare_unfenced() {
        // This is quark's verbatim ReviewResult from exec exec_18b5da2a31922490_161.
        // The text is the DECODED reviewer message (what read_final_triage_message
        // returns after parsing the JSONL transcript). The JSON is bare — no fence.
        let bare_json = r#"{
"pr_url": "https://github.com/spinyfin/mono/pull/1361",
"head_sha": "0caebb932d3cd7af212cb7bf31592e8801bcf365",
"summary": "The PR correctly swaps GitHub's --generate-notes for bin/changelog in both the boss and checkleft release steps, reusing the existing per-product LAST_TAG/NEW_TAG (no global-latest-tag regression), routing through repobin dispatch (changelog is registered in REPOBIN.toml; --no-defaults only skips writing repobin.yaml, symlinks for configured tools including changelog are still created), and the --project/--from/--to/--repo/--enrich flags all match tools/changelog's CLI. Two substantive issues remain. (1) The changelog extracts commits with a LOCAL `git log <from>..<to>` (tools/changelog/src/extract.rs get_commits), which succeeds-but-truncates on a shallow Buildkite checkout; the repo is only unshallowed on the non-manual change-detection path, so manual (ui/api) releases — and the LAST_SHA-unresolved cron edge — can silently produce an incomplete/empty release body. (2) In boss-release.sh the new `bazel build`/changelog block is placed AFTER `trap - ERR` is removed and is not covered by the EXIT trap (which only removes WORK_DIR), so a failure there leaks the already-pushed boss-v* tag with no release and no cleanup, wedging subsequent releases on a duplicate-tag push; checkleft handles the equivalent window correctly via its cleanup() EXIT trap (TAG_PUSHED guard). No unrelated features were dropped.",
"revision_warranted": true,
"findings": [
{
"severity": "high",
"category": "correctness",
"file": ".buildkite/steps/checkleft-release.sh",
"location": "phase_prepare, ~L336-351 (and boss-release.sh ~L297-311)",
"title": "changelog reads local git history that isn't unshallowed on manual releases → silently truncated notes",
"detail": "The changelog tool builds the body from a local `git log <LAST_TAG>..<NEW_TAG>` (tools/changelog/src/extract.rs get_commits, line ~147). The old `gh release create --generate-notes` computed notes server-side from GitHub, so a shallow Buildkite checkout was fine; the new approach needs the full local commit range. The repo is only unshallowed inside the change-detection path (checkleft should_skip L246-248, boss L96-98), which is SKIPPED for manual (ui/api) triggers (checkleft is_manual returns early at L232-235; boss skips at L85-86) and is also skipped on the cron edge where LAST_SHA fails to resolve (boss L92-93 'proceeds'). git log on a shallow clone returns success with a truncated/empty set rather than failing, so the release body is silently wrong — directly violating the acceptance criterion that the body contain ALL product-owned commits in the range. Fix: before invoking changelog (when LAST_TAG is non-empty), ensure full history, e.g. `if git rev-parse --is-shallow-repository | grep -q true; then git fetch --unshallow origin || true; fi`, in BOTH scripts, so every trigger path (manual included) renders the complete range.",
"confidence": "medium"
},
{
"severity": "medium",
"category": "correctness",
"file": ".buildkite/steps/boss-release.sh",
"location": "~L280-318 (after `trap - ERR`)",
"title": "boss: fallible `bazel build`/changelog runs after tag-cleanup trap is disarmed → leaked tag wedges future releases",
"detail": "The new notes-generation block (L297-311), which includes `bazel build //tools/repobin:repobin` and the changelog dispatch (itself another bazel build), runs AFTER `trap - ERR` is cleared at L280. The only remaining trap is the EXIT handler set at L288, which removes WORK_DIR but does NOT delete the pushed tag. So if repobin/changelog build or `bin/changelog` fails under `set -e`, the script aborts with boss-v1.0.N already pushed (L199) and no release created or cleaned up. Because the next run computes the version from `gh release list` (L167, releases not tags), it recomputes the same N and `git push origin refs/tags/boss-v1.0.N` (L199) then fails on the pre-existing remote tag — permanently blocking boss releases until someone manually deletes the orphan tag. checkleft avoids this: its cleanup() EXIT trap deletes the leaked tag while TAG_PUSHED=1 (reset to 0 only after the release is created, L361). Fix: in boss, either generate the notes before pushing the tag / before `trap - ERR` (the changelog only needs the LOCAL tag created at L198, so it can run earlier under ERR-trap protection), or extend the EXIT trap to delete the pushed tag if the release was never created.",
"confidence": "medium"
},
{
"severity": "low",
"category": "edgecase",
"file": ".buildkite/steps/boss-release.sh",
"location": "~L298-318 (and checkleft ~L338-357)",
"title": "Notes temp file leaks when `gh release create` fails",
"detail": "`rm -f \"${NOTES_FILE}\"` (boss L318) / `rm -f \"${notes_file}\"` (checkleft L357) runs only after a successful `gh release create`; under `set -e` a failed release create skips the rm, leaving /tmp/*-release-notes-*.md behind. Minor, but easily made robust by registering the temp file in the existing EXIT trap (boss already has one for WORK_DIR; checkleft's cleanup() could `rm -f` it) instead of an inline rm.",
"confidence": "high"
}
],
"regression_check": {
"performed": true,
"suspected_deletions": []
}
}"#;

        let result =
            extract_review_result(bare_json).expect("T1359 exact quark JSON (bare, unfenced) must parse successfully");
        assert!(result.revision_warranted, "revision_warranted must be true");
        assert!(
            result
                .findings
                .iter()
                .any(|f| matches!(f.severity, ReviewFindingSeverity::High)),
            "high-severity finding must be present",
        );
        assert!(
            result
                .findings
                .iter()
                .any(|f| matches!(f.category, ReviewFindingCategory::Correctness)),
            "correctness finding must be present",
        );
    }

    /// Regression test for T1359: bare JSON with RICH text in summary/detail
    /// fields — bash code, escaped quotes, `${VAR}` syntax, and backtick fences
    /// embedded in the finding's `detail`. This mimics the quark reviewer output
    /// that defeated the original bare-JSON scanner.
    ///
    /// The scanner must correctly skip braces inside JSON string literals
    /// even when the strings contain `${...}`, `\"`, and backtick code blocks.
    #[test]
    fn extract_review_result_bare_json_rich_text_with_embedded_code_and_braces() {
        // Construct a JSON that closely resembles what quark emitted for T1359.
        // The `detail` field contains bash code with `${TAG}` syntax (braces inside
        // a JSON string literal) and escaped quotes — the suspected failure vector.
        let json = serde_json::json!({
            "pr_url": "https://github.com/brianduff/mono/pull/1361",
            "head_sha": "deadbeef",
            "summary": "Found a correctness bug in tools/boss/release/boss-release.sh. The script creates a git tag before pushing it (~L42), but if `git push --tags` fails the orphan tag persists locally. On the next release attempt the script would fail with \"tag already exists\".",
            "revision_warranted": true,
            "findings": [
                {
                    "severity": "high",
                    "category": "correctness",
                    "file": "tools/boss/release/boss-release.sh",
                    "location": "~L42-52",
                    "title": "Orphan tag leak when git push fails",
                    "detail": "The script creates the tag before verifying the push:\n\n```bash\ngit tag -a \"${TAG}\" -m \"Release ${TAG}\"\ngit push --tags\n```\n\nIf `git push --tags` fails (auth error, network timeout) the local tag persists. The next run hits \"fatal: tag '${TAG}' already exists\". Fix: tag AFTER push, or clean up on failure with `git push --tags || git tag -d \"${TAG}\"`.",
                    "confidence": "high"
                },
                {
                    "severity": "medium",
                    "category": "correctness",
                    "file": "tools/boss/release/boss-release.sh",
                    "title": "Missing set -euo pipefail",
                    "detail": "No `set -euo pipefail` at the top; a failed intermediate command silently continues. Add it as the first non-comment line.",
                    "confidence": "medium"
                }
            ],
            "regression_check": {
                "performed": true,
                "suspected_deletions": []
            }
        })
        .to_string();

        // Emit the JSON BARE — no code fence anywhere in the message (T1359 shape).
        let text = format!(
            "I reviewed PR #1361. Key findings:\n\n\
             The main issue is an orphan-tag leak in the release script. \
             Full structured result:\n\n{json}"
        );
        let result =
            extract_review_result(&text).expect("rich bare-JSON ReviewResult must be extracted (T1359 regression)");
        assert!(result.revision_warranted, "revision_warranted must be true");
        assert_eq!(result.findings.len(), 2, "must recover both findings");
        assert_eq!(
            result.findings[0].severity,
            ReviewFindingSeverity::High,
            "first finding must be high severity",
        );
        assert_eq!(result.findings[0].category, ReviewFindingCategory::Correctness,);
    }

    /// Regression fixture for T1359: when the bare JSON is preceded by prose
    /// that contains `${VARIABLE}` syntax (which contains `{` and `}` characters),
    /// the scanner must NOT be confused by those brace pairs and must still find
    /// the actual ReviewResult that follows.
    #[test]
    fn extract_review_result_bare_json_with_braces_in_preceding_prose() {
        let json = serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/99",
            "head_sha": "deadbeef",
            "summary": "Found issue with variable substitution.",
            "revision_warranted": true,
            "findings": [
                {
                    "severity": "high",
                    "category": "correctness",
                    "file": "script.sh",
                    "title": "Orphan tag leak",
                    "detail": "The call `git tag -a \"${TAG}\"` runs before the push check.",
                    "confidence": "high"
                }
            ],
            "regression_check": {
                "performed": true,
                "suspected_deletions": []
            }
        })
        .to_string();

        // Prose BEFORE the JSON contains ${TAG} and ${RELEASE} — braces that
        // must not confuse the balanced-brace scanner.
        let text = format!(
            "The release script sets TAG=${{TAG}} and runs `git push ${{RELEASE}}`.\n\n\
             If the push fails, the local tag at ${{TAG}} persists.\n\n{json}"
        );
        let result =
            extract_review_result(&text).expect("ReviewResult must be found even when preceding prose has bare braces");
        assert!(result.revision_warranted);
        assert_eq!(result.findings.len(), 1);
    }

    /// Regression fixture for T1687/PR#1497: reviewer correctly identifies a
    /// regression but fills `suspected_deletions` with descriptive strings
    /// instead of `ReviewFinding` objects (because the prompt schema never
    /// showed the element shape). Previously `serde_json::from_str` rejected
    /// the ENTIRE `ReviewResult` with "invalid type: string, expected struct
    /// ReviewFinding", silently dropping the finding.
    ///
    /// After the fix (`#[serde(skip_deserializing)]` on `suspected_deletions`
    /// plus derivation from `findings` in `from_json`) the JSON must parse and
    /// `passes_severity_gate` must fire.
    #[test]
    fn suspected_deletions_string_array_accepted_and_derived_from_findings() {
        let json = serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/42",
            "head_sha": "abc123",
            "summary": "Found a regression — config exclude rule removed.",
            "revision_warranted": true,
            "findings": [
                {
                    "severity": "high",
                    "category": "regression",
                    "file": "CHECKS.yaml",
                    "title": "Config exclude rule dropped without replacement",
                    "detail": "The config_dir-scoped exclude_files rule was removed.",
                    "confidence": "high"
                }
            ],
            "regression_check": {
                "performed": true,
                // Reviewer emitted a string array — the T1687 shape that
                // previously caused a serde type-mismatch rejection.
                "suspected_deletions": [
                    "config_dir-scoped exclude_files matching removed without replacement"
                ]
            }
        })
        .to_string();

        let result = ReviewResult::from_json(&json)
            .expect("ReviewResult with string-array suspected_deletions must parse (T1687 fix)");
        assert!(result.revision_warranted, "revision_warranted must be preserved");
        assert_eq!(result.findings.len(), 1, "finding must be preserved");
        assert!(
            passes_severity_gate(&result),
            "high-severity regression must pass the severity gate",
        );
        // Engine derives suspected_deletions from the regression finding.
        assert_eq!(
            result.regression_check.suspected_deletions.len(),
            1,
            "engine must derive one suspected_deletion from the regression finding",
        );
        assert_eq!(
            result.regression_check.suspected_deletions[0].title,
            "Config exclude rule dropped without replacement",
        );
    }

    /// Deriving `suspected_deletions` from `findings` must work when there are
    /// no regression-category findings — the field stays empty.
    #[test]
    fn suspected_deletions_empty_when_no_regression_findings() {
        let json = serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/1",
            "head_sha": "abc",
            "summary": "ok",
            "revision_warranted": false,
            "findings": [
                {
                    "severity": "medium",
                    "category": "readability",
                    "file": "a.rs",
                    "title": "style nit",
                    "detail": "consider renaming",
                    "confidence": "low"
                }
            ],
            "regression_check": {"performed": true, "suspected_deletions": []}
        })
        .to_string();

        let result = ReviewResult::from_json(&json).expect("parses");
        assert!(
            result.regression_check.suspected_deletions.is_empty(),
            "no regression findings → suspected_deletions must be empty",
        );
    }

    /// `extract_review_result_verbose` must return the serde error text when a
    /// fenced JSON block is present but fails to deserialize as `ReviewResult`.
    /// The error text is used in the reviewer re-prompt so the reviewer can
    /// correct the specific malformation rather than blindly rewriting.
    #[test]
    fn extract_review_result_verbose_returns_error_on_malformed_fenced_json() {
        // findings is a string instead of an array — valid JSON but wrong type.
        let text = concat!(
            "Here is my review:\n\n```json\n",
            "{\"pr_url\":\"https://github.com/org/repo/pull/1\",",
            "\"head_sha\":\"abc\",\"summary\":\"s\",\"revision_warranted\":true,",
            "\"findings\":\"not-an-array\",",
            "\"regression_check\":{\"performed\":true,\"suspected_deletions\":[]}}\n",
            "```\n"
        );
        let (result, err) = extract_review_result_verbose(text);
        assert!(result.is_none(), "malformed JSON must not produce a result");
        let err_text = err.expect("error text must be returned for a malformed fenced block");
        assert!(!err_text.is_empty(), "error text must not be empty; got: {err_text}",);
    }

    // --- passes_severity_gate ---

    fn make_finding(severity: ReviewFindingSeverity, category: ReviewFindingCategory) -> ReviewFinding {
        ReviewFinding::builder()
            .severity(severity)
            .category(category)
            .file("src/lib.rs")
            .title("test finding")
            .detail("something concrete")
            .confidence(ReviewFindingConfidence::High)
            .build()
    }

    #[test]
    fn severity_gate_passes_on_critical() {
        let result = ReviewResult {
            pr_url: String::new(),
            head_sha: String::new(),
            summary: String::new(),
            revision_warranted: false,
            findings: vec![make_finding(
                ReviewFindingSeverity::Critical,
                ReviewFindingCategory::Correctness,
            )],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        assert!(passes_severity_gate(&result));
    }

    #[test]
    fn severity_gate_passes_on_high() {
        let result = ReviewResult {
            pr_url: String::new(),
            head_sha: String::new(),
            summary: String::new(),
            revision_warranted: false,
            findings: vec![make_finding(
                ReviewFindingSeverity::High,
                ReviewFindingCategory::Architecture,
            )],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        assert!(passes_severity_gate(&result));
    }

    #[test]
    fn severity_gate_passes_on_regression_regardless_of_severity() {
        let result = ReviewResult {
            pr_url: String::new(),
            head_sha: String::new(),
            summary: String::new(),
            revision_warranted: false,
            findings: vec![make_finding(
                ReviewFindingSeverity::Low,
                ReviewFindingCategory::Regression,
            )],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        assert!(passes_severity_gate(&result));
    }

    #[test]
    fn severity_gate_blocked_on_medium_non_regression() {
        let result = ReviewResult {
            pr_url: String::new(),
            head_sha: String::new(),
            summary: String::new(),
            revision_warranted: true, // reviewer says warranted but engine gate disagrees
            findings: vec![make_finding(
                ReviewFindingSeverity::Medium,
                ReviewFindingCategory::Readability,
            )],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        assert!(!passes_severity_gate(&result));
    }

    #[test]
    fn severity_gate_blocked_on_empty_findings() {
        let result = ReviewResult {
            pr_url: String::new(),
            head_sha: String::new(),
            summary: String::new(),
            revision_warranted: false,
            findings: vec![],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        assert!(!passes_severity_gate(&result));
    }

    // --- render_revision_instructions ---

    #[test]
    fn render_revision_instructions_contains_title_and_detail() {
        let result = ReviewResult {
            pr_url: "https://github.com/org/repo/pull/5".to_owned(),
            head_sha: String::new(),
            summary: "One bug found.".to_owned(),
            revision_warranted: true,
            findings: vec![
                ReviewFinding::builder()
                    .severity(ReviewFindingSeverity::High)
                    .category(ReviewFindingCategory::Correctness)
                    .file("src/main.rs")
                    .location("fn handle, ~L42")
                    .title("Null pointer dereference")
                    .detail("The handle function dereferences without a null check; add a guard.")
                    .confidence(ReviewFindingConfidence::High)
                    .build(),
            ],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        let instructions = render_revision_instructions(&result);
        assert!(instructions.contains("Null pointer dereference"));
        assert!(instructions.contains("src/main.rs"));
        assert!(instructions.contains("fn handle, ~L42"));
        assert!(instructions.contains("add a guard"));
        assert!(instructions.contains("One bug found."));
        assert!(instructions.contains("high")); // severity
    }

    #[test]
    fn render_revision_instructions_sorts_by_severity() {
        let result = ReviewResult {
            pr_url: String::new(),
            head_sha: String::new(),
            summary: String::new(),
            revision_warranted: true,
            findings: vec![
                ReviewFinding::builder()
                    .severity(ReviewFindingSeverity::Low)
                    .category(ReviewFindingCategory::Readability)
                    .file("a.rs")
                    .title("Low finding")
                    .detail("minor")
                    .confidence(ReviewFindingConfidence::Low)
                    .build(),
                ReviewFinding::builder()
                    .severity(ReviewFindingSeverity::Critical)
                    .category(ReviewFindingCategory::Correctness)
                    .file("b.rs")
                    .title("Critical finding")
                    .detail("urgent")
                    .confidence(ReviewFindingConfidence::High)
                    .build(),
            ],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        let instructions = render_revision_instructions(&result);
        let critical_pos = instructions.find("Critical finding").expect("present");
        let low_pos = instructions.find("Low finding").expect("present");
        assert!(critical_pos < low_pos, "critical must appear before low");
    }
}
