//! Reviewer worker: initial-prompt rendering and `ReviewResult` structured
//! output (design §2 and §3 of P992 "Automated reviewer pass on every
//! agent-authored PR").
//!
//! # Role
//!
//! A reviewer worker is a `pr_review` execution dispatched to the dedicated
//! review pool. It operates **read-only**: it reads the PR diff and changed
//! files, produces structured `ReviewResult` JSON, and never writes, commits,
//! pushes, or posts to GitHub. The read-only mandate is enforced at three
//! layers (design §9):
//!
//! 1. **Reviewer CLAUDE.md** — generated by
//!    [`crate::worker_setup::render_claude_md`] when `worker_kind =
//!    WorkerKind::Reviewer`; states the mandate prominently.
//! 2. **Tool denylist** — [`crate::worker_setup::reviewer_deny_rules`],
//!    wired to `WorkerKind::Reviewer` in the settings file.
//! 3. **Prompt mandate** — [`render_reviewer_initial_prompt`] repeats the
//!    read-only constraint in the task prompt alongside the review rubric.
//!
//! # Output contract
//!
//! The reviewer emits exactly one `ReviewResult` JSON object in a fenced
//! ` ```json ` block in its final message. The completion handler (task 8)
//! extracts and parses this block. The `ReviewResult` is the sole
//! deliverable; the reviewer must not emit any other action.

use serde::{Deserialize, Serialize};

/// Severity of a review finding — drives the engine's revision-warrant
/// decision (design §3: any `critical`/`high`, or any `regression`,
/// creates a revision regardless of `revision_warranted`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewFindingSeverity {
    Critical,
    High,
    Medium,
    Low,
}

impl ReviewFindingSeverity {
    /// Return the string label used in the prompt schema description.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Critical => "critical",
            Self::High => "high",
            Self::Medium => "medium",
            Self::Low => "low",
        }
    }
}

/// What kind of issue a finding represents.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewFindingCategory {
    /// Logic error, broken invariant, race condition, mishandled error.
    Correctness,
    /// Inadvertent deletion/regression — code dropped that was not the
    /// purpose of the PR (the T793 check class).
    Regression,
    /// Wrong layer, missed reuse, abstraction fights codebase conventions.
    Architecture,
    /// Style, naming, dead/confusing code, fails to match surroundings.
    Readability,
    /// Untested new behaviour, missing edge-case test.
    Tests,
    /// Boundary condition, nullability, concurrency, failure mode.
    #[serde(rename = "edgecase")]
    EdgeCase,
}

/// Reviewer's confidence in a finding.
///
/// `Low` means "suggestion — apply at the revising worker's discretion;
/// this alone does not warrant a revision cycle".
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewFindingConfidence {
    High,
    Medium,
    Low,
}

/// A single actionable review finding.
///
/// Every finding must name a file and state concretely what to change.
/// Vague findings ("consider improving error handling") are not acceptable.
#[derive(Debug, Clone, Serialize, Deserialize, bon::Builder)]
#[builder(on(String, into))]
pub struct ReviewFinding {
    pub severity: ReviewFindingSeverity,
    pub category: ReviewFindingCategory,
    /// File path relative to the repo root.
    pub file: String,
    /// Best-effort location within the file (function name, ~line, hunk).
    /// `None` when the finding applies to the file as a whole.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Short, scannable title (≤ 80 chars).
    pub title: String,
    /// Concrete description of the problem **and** what to change. Must be
    /// specific enough that the revising worker can act without guessing.
    pub detail: String,
    pub confidence: ReviewFindingConfidence,
}

/// First-class regression/deletion check — always present in `ReviewResult`.
///
/// `performed` must be `true`; the reviewer cannot skip the deletion check.
/// If it finds no regressions, it returns `suspected_deletions: []` with
/// `performed: true`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegressionCheck {
    /// Always `true`. The reviewer must always perform the deletion check.
    pub performed: bool,
    /// All `category = "regression"` findings extracted from `findings`.
    pub suspected_deletions: Vec<ReviewFinding>,
}

/// Structured output emitted by the reviewer worker in a ```json fenced block
/// in its final message (design §3).
///
/// The engine completion handler extracts this JSON from the final message,
/// parses it, and applies the severity gate to decide whether to create a
/// revision on the producing task. `revision_warranted = false` with no
/// qualifying findings → PR proceeds to human Review unimpeded.
#[derive(Debug, Clone, Serialize, Deserialize, bon::Builder)]
#[builder(on(String, into))]
pub struct ReviewResult {
    /// URL of the PR that was reviewed.
    pub pr_url: String,
    /// HEAD SHA of the PR at review time — used for no-op detection (design
    /// §8) and to guard against racing updates. Best-effort; the engine
    /// tolerates an empty string if `gh pr view` did not supply one.
    pub head_sha: String,
    /// One-paragraph overall assessment of the PR.
    pub summary: String,
    /// Whether the reviewer believes a revision is warranted. The engine
    /// additionally gates on its own severity threshold (any critical/high
    /// or any regression finding forces a revision regardless of this flag).
    pub revision_warranted: bool,
    /// All findings, ordered by severity (critical first, low last).
    pub findings: Vec<ReviewFinding>,
    /// First-class regression/deletion check — always present.
    pub regression_check: RegressionCheck,
}

impl ReviewResult {
    /// Parse a `ReviewResult` from a JSON string.
    ///
    /// The completion handler calls this after extracting the ```json fenced
    /// block from the reviewer's final message.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }
}

/// Render the CLAUDE.md for a reviewer worker (design §9 of P992).
///
/// Reviewer workers operate **read-only**: they read PR diffs and workspace
/// files but must not write, push, or post to GitHub. This CLAUDE.md
/// prominently states that mandate and omits PR-creation / VCS-push
/// guidance entirely (those actions are also blocked by the reviewer denylist,
/// so this is the belt that accompanies that suspenders layer).
pub fn render_reviewer_claude_md(lease_id: &str) -> String {
    format!(
        "# Boss reviewer rules\n\
         \n\
         You are running inside a Boss-managed **reviewer** session. The engine\n\
         spawned you in a leased cube workspace to review a PR read-only.\n\
         \n\
         ## Read-only mandate (HARD CONSTRAINT)\n\
         \n\
         **You MUST NOT change the PR or its branch in any way.**\n\
         \n\
         Forbidden actions (tool calls for these are denied):\n\
         \n\
         - Writing or editing any file (`Edit`, `Write`).\n\
         - Committing or pushing (`jj git push`, `git push`).\n\
         - Opening, merging, closing, editing, or commenting on a PR\n\
           (`gh pr create/merge/close/edit/comment/review`).\n\
         - Interacting with GitHub issues in any write capacity.\n\
         - Running `cube pr ensure` or any Boss PR helper.\n\
         \n\
         Anything you would \"fix\", describe as a finding in the\n\
         `ReviewResult` JSON instead. Your feedback stays inside Boss —\n\
         **it is never posted to GitHub**.\n\
         \n\
         Allowed read-only tools: `grep`, `find`, `cat`, `head`, `tail`,\n\
         `jj log`, `jj show`, `jj diff`, `gh pr view`, `gh pr diff`,\n\
         `gh pr list`, and similar read-only operations.\n\
         \n\
         ## Your workspace\n\
         \n\
         - Cube lease id: `{lease}`\n\
         \n\
         Lease held for the lifetime of this run. Do not lease, release,\n\
         or mutate cube state.\n\
         \n\
         ## VCS (read-only)\n\
         \n\
         Use `jj` for read-only navigation. Do not push or modify history.\n\
         \n\
         - `jj log`, `jj show`, `jj diff` — browse history and diffs.\n\
         - `gh pr diff <url>` — fetch the PR diff.\n\
         - `gh pr view <url>` — read the PR description.\n\
         \n\
         ## Boundaries\n\
         \n\
         - Do not modify files outside your workspace. Other workspaces\n\
           belong to other workers.\n\
         - Do not modify cube's database, lease state, or workspace registry.\n\
         - `~/Library/Application Support/Boss/` is coordinator/engine-only.\n\
           Never read, write, or touch it.\n\
           `bossctl` is coordinator-only.\n\
         \n\
         ## Coordinator\n\
         \n\
         The coordinator may probe this session between turns. Treat probes\n\
         as questions from a human reviewer — short, specific answers.\n",
        lease = lease_id,
    )
}

/// Compose the initial-prompt for a `pr_review` execution (design §2).
///
/// `task_name` and `task_description` are the producing task's title and
/// description — they tell the reviewer what the PR was *supposed* to do,
/// which is the baseline for the regression/deletion check.
///
/// `pr_url` is the PR to review. The reviewer fetches the diff via
/// `gh pr diff` and reads changed files for context.
pub fn render_reviewer_initial_prompt(
    task_name: &str,
    task_description: &str,
    pr_url: &str,
) -> String {
    format!(
        "# PR review\n\
         \n\
         You are an independent PR reviewer. Your ONLY job is to review the \
         PR and return a single structured `ReviewResult` JSON. You MUST NOT \
         change the PR in any way: no commits, no pushes, no `gh` writes, no \
         edits to any file or branch, no comments on GitHub. You operate \
         **read-only**. Anything you would \"fix\" you instead describe as a \
         finding. Posting to GitHub is prohibited — your feedback stays inside \
         Boss as an internal revision.\n\
         \n\
         ## PR under review\n\
         \n\
         **Task:** {task_name}\n\
         \n\
         **Task description:**\n\
         {task_description}\n\
         \n\
         **PR:** {pr_url}\n\
         \n\
         ## Review steps\n\
         \n\
         1. Get the diff: `gh pr diff {pr_url}`\n\
         2. Get the PR description: `gh pr view {pr_url}`\n\
         3. Read changed files as needed for context (use `cat`, `grep`, `jj \
            show`, etc. — no writes).\n\
         4. Produce the `ReviewResult` JSON (schema below) in a fenced \
            ` ```json ` block as the **last thing in your final message**.\n\
         \n\
         ## Review rubric — code PR\n\
         \n\
         Apply a **high bar**: push back only on real problems, not \
         stylistic preferences. Every finding must name a file (and \
         function/line/hunk where possible) and state **concretely what to \
         change**. Vague findings are not acceptable.\n\
         \n\
         Review for:\n\
         \n\
         - **Critical correctness** — logic errors, broken invariants, \
           mishandled errors, race conditions. (`category: \"correctness\"`)\n\
         - **Inadvertent regressions** *(first-class, explicit check)* — \
           diff against `main` and flag anything dropped that is unrelated \
           to the PR's stated purpose. Conflict-resolution and forward-port \
           PRs get extra scrutiny here. This is the T793 check: a live \
           feature silently removed during a forward-port must be caught. \
           (`category: \"regression\"`)\n\
         - **Architectural issues** — wrong layer, missed reuse, abstraction \
           that fights the codebase's conventions. (`category: \
           \"architecture\"`)\n\
         - **Code quality/readability** — fails to match surrounding style, \
           naming issues, dead/confusing code. (`category: \"readability\"`)\n\
         - **Test coverage gaps** — untested new behaviour, missing \
           edge-case tests. (`category: \"tests\"`)\n\
         - **Edge cases/gotchas** — boundary conditions, nullability, \
           concurrency, failure modes. (`category: \"edgecase\"`)\n\
         \n\
         ## Docs-only PR rubric\n\
         \n\
         If the diff contains **only** Markdown/documentation files (`.md`, \
         design docs, READMEs, etc.) with no source-code changes, switch to \
         the light rubric:\n\
         \n\
         - Structure and completeness of the document.\n\
         - Internal consistency (no contradictions within the doc).\n\
         - Required-sections check for design docs (problem/goals/approach \
           headings present).\n\
         \n\
         Do NOT apply the code rubric (tests, regressions, architecture) to \
         a pure docs PR.\n\
         \n\
         ## Speed/comprehensiveness balance\n\
         \n\
         Prefer **fast, high-signal feedback** over exhaustive analysis. \
         Every PR may now pass through up to ~3 produce→review→revise cycles, \
         so do NOT excessively lengthen turnaround. Spend your scrutiny budget \
         on correctness and regressions first. If in doubt about a \
         non-critical suggestion, you MAY offer it WITHOUT deep analysis \
         and mark it `low` severity and `low` confidence — the revising \
         worker decides whether to apply it.\n\
         \n\
         ## Required output\n\
         \n\
         Emit exactly one `ReviewResult` JSON in a ` ```json ` fenced block \
         as the last thing in your response. No other terminal action is \
         permitted.\n\
         \n\
         Schema:\n\
         \n\
         ```jsonc\n\
         {{\n\
           \"pr_url\": \"{pr_url}\",\n\
           \"head_sha\": \"<sha from gh pr view --json headRefOid>\",\n\
           \"summary\": \"<one-paragraph overall assessment>\",\n\
           \"revision_warranted\": true,\n\
           \"findings\": [\n\
             {{\n\
               \"severity\": \"critical | high | medium | low\",\n\
               \"category\": \"correctness | regression | architecture | readability | tests | edgecase\",\n\
               \"file\": \"path/to/file.rs\",\n\
               \"location\": \"fn foo, ~L42\",\n\
               \"title\": \"<short scannable title>\",\n\
               \"detail\": \"<concrete description + what to change>\",\n\
               \"confidence\": \"high | medium | low\"\n\
             }}\n\
           ],\n\
           \"regression_check\": {{\n\
             \"performed\": true,\n\
             \"suspected_deletions\": []\n\
           }}\n\
         }}\n\
         ```\n\
         \n\
         Rules:\n\
         \n\
         - `revision_warranted`: set to `true` when there is at least one \
           finding at `critical`/`high` severity, or any finding with \
           `category: \"regression\"`, regardless of severity. Set to `false` \
           for findings that are purely `medium`/`low` correctness/style \
           (the engine applies its own gate on top).\n\
         - `regression_check.performed` MUST be `true` — you cannot skip the \
           deletion check. If you find no regressions, set \
           `suspected_deletions: []`.\n\
         - `findings` may be empty if the PR is clean. `revision_warranted` \
           must then be `false`.\n\
         - `location` is optional (omit the key if the finding applies to the \
           whole file).\n\
         - Do NOT post this JSON to GitHub or as a PR comment. It stays \
           inside Boss.\n",
        task_name = task_name,
        task_description = task_description,
        pr_url = pr_url,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn review_result_roundtrips_through_json() {
        let result = ReviewResult {
            pr_url: "https://github.com/org/repo/pull/42".to_owned(),
            head_sha: "abc123def456".to_owned(),
            summary: "Overall the PR looks good with one regression.".to_owned(),
            revision_warranted: true,
            findings: vec![ReviewFinding {
                severity: ReviewFindingSeverity::High,
                category: ReviewFindingCategory::Regression,
                file: "tools/boss/engine/src/lib.rs".to_owned(),
                location: Some("fn init, ~L10".to_owned()),
                title: "Forward-port dropped the autostart feature".to_owned(),
                detail: "The autostart flag was removed in the conflict resolution; \
                         restore it."
                    .to_owned(),
                confidence: ReviewFindingConfidence::High,
            }],
            regression_check: RegressionCheck {
                performed: true,
                suspected_deletions: vec![],
            },
        };
        let json = serde_json::to_string(&result).expect("serializes");
        let parsed = ReviewResult::from_json(&json).expect("deserializes");
        assert_eq!(parsed.pr_url, result.pr_url);
        assert_eq!(parsed.head_sha, result.head_sha);
        assert!(parsed.revision_warranted);
        assert_eq!(parsed.findings.len(), 1);
        assert_eq!(parsed.findings[0].severity, ReviewFindingSeverity::High);
        assert_eq!(
            parsed.findings[0].category,
            ReviewFindingCategory::Regression
        );
        assert!(parsed.regression_check.performed);
    }

    #[test]
    fn review_result_empty_findings_deserializes() {
        let json = serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/7",
            "head_sha": "",
            "summary": "LGTM, no issues found.",
            "revision_warranted": false,
            "findings": [],
            "regression_check": {
                "performed": true,
                "suspected_deletions": []
            }
        });
        let result = ReviewResult::from_json(&json.to_string()).expect("deserializes");
        assert!(!result.revision_warranted);
        assert!(result.findings.is_empty());
        assert!(result.regression_check.performed);
    }

    #[test]
    fn reviewer_initial_prompt_contains_rubric_and_pr_url() {
        let prompt = render_reviewer_initial_prompt(
            "Fix the auth bug",
            "Auth middleware drops sessions on timeout.",
            "https://github.com/org/repo/pull/99",
        );
        assert!(prompt.contains("https://github.com/org/repo/pull/99"));
        assert!(prompt.contains("Fix the auth bug"));
        assert!(prompt.contains("Auth middleware drops sessions on timeout."));
        assert!(prompt.contains("regression"));
        assert!(prompt.contains("correctness"));
        assert!(prompt.contains("revision_warranted"));
        assert!(prompt.contains("regression_check"));
        assert!(prompt.contains("read-only"));
        assert!(prompt.contains("gh pr diff"));
    }

    #[test]
    fn reviewer_initial_prompt_contains_docs_rubric() {
        let prompt = render_reviewer_initial_prompt(
            "Add design doc",
            "Write a design doc for feature X.",
            "https://github.com/org/repo/pull/100",
        );
        assert!(prompt.contains("Docs-only"));
        assert!(prompt.contains("light rubric"));
        assert!(prompt.contains("Markdown"));
    }

    #[test]
    fn reviewer_initial_prompt_states_speed_balance() {
        let prompt = render_reviewer_initial_prompt("T", "D", "https://github.com/pr/1");
        assert!(prompt.contains("fast, high-signal"));
        assert!(prompt.contains("scrutiny budget"));
    }

    #[test]
    fn review_finding_severity_roundtrips_as_snake_case() {
        for (sev, expected) in [
            (ReviewFindingSeverity::Critical, "\"critical\""),
            (ReviewFindingSeverity::High, "\"high\""),
            (ReviewFindingSeverity::Medium, "\"medium\""),
            (ReviewFindingSeverity::Low, "\"low\""),
        ] {
            let json = serde_json::to_string(&sev).unwrap();
            assert_eq!(json, expected);
            let back: ReviewFindingSeverity = serde_json::from_str(&json).unwrap();
            assert_eq!(back, sev);
        }
    }

    #[test]
    fn review_finding_category_roundtrips_as_snake_case() {
        for (cat, expected) in [
            (ReviewFindingCategory::Correctness, "\"correctness\""),
            (ReviewFindingCategory::Regression, "\"regression\""),
            (ReviewFindingCategory::Architecture, "\"architecture\""),
            (ReviewFindingCategory::Readability, "\"readability\""),
            (ReviewFindingCategory::Tests, "\"tests\""),
            (ReviewFindingCategory::EdgeCase, "\"edgecase\""),
        ] {
            let json = serde_json::to_string(&cat).unwrap();
            assert_eq!(json, expected);
            let back: ReviewFindingCategory = serde_json::from_str(&json).unwrap();
            assert_eq!(back, cat);
        }
    }

    #[test]
    fn regression_check_performed_must_be_true_in_valid_result() {
        let json = serde_json::json!({
            "pr_url": "https://github.com/org/repo/pull/1",
            "head_sha": "abc",
            "summary": "ok",
            "revision_warranted": false,
            "findings": [],
            "regression_check": {
                "performed": true,
                "suspected_deletions": []
            }
        });
        let result = ReviewResult::from_json(&json.to_string()).unwrap();
        assert!(result.regression_check.performed);
    }
}
