use anyhow::{Context, Result, bail};
use async_trait::async_trait;
use globset::{Glob, GlobSet, GlobSetBuilder};
use serde::Deserialize;
use std::sync::Arc;

use crate::check::{Check, ConfiguredCheck};
use crate::input::{ChangeKind, ChangeSet, SourceTree};
use crate::output::{CheckResult, Finding, Location, Severity};

const CHECK_ID: &str = "rust-giant-structs-use-builder";
const DEFAULT_MAX_FIELDS: usize = 5;

/// Flags Rust structs with more named fields than `max_fields` (default 5, meaning 6+)
/// that do not carry the required builder derive. Tuple and unit structs are exempt.
/// Structs inside `#[cfg(test)]` modules and structs with `#[cfg(test)]` on themselves
/// are also exempt. Structs generated by macros are invisible to syn and thus not checked.
///
/// To permanently exempt a file (e.g. for grandfathered violations), add it to
/// `exclude_globs` in the check config. For a one-off exception in a PR, use:
///   BYPASS_RUST_GIANT_STRUCTS_USE_BUILDER=<specific reason>
/// in the PR or commit description (requires `allow_bypass = true` in policy).
pub struct RustGiantStructsUseBuilderCheck;

#[derive(Debug, Deserialize, Default)]
struct RawConfig {
    #[serde(default)]
    max_fields: Option<i64>,
    #[serde(default)]
    builder: Option<String>,
    #[serde(default)]
    exclude_globs: Option<Vec<String>>,
}

struct ParsedConfig {
    max_fields: usize,
    builder: BuilderKind,
    exclude_globs: Option<GlobSet>,
}

#[derive(Clone, Debug)]
enum BuilderKind {
    Bon,
    DeriveBuilder,
}

impl BuilderKind {
    fn derive_display(&self) -> &str {
        match self {
            Self::Bon => "bon::Builder",
            Self::DeriveBuilder => "derive_builder::Builder",
        }
    }

    fn crate_name(&self) -> &str {
        match self {
            Self::Bon => "bon",
            Self::DeriveBuilder => "derive_builder",
        }
    }
}

#[async_trait]
impl Check for RustGiantStructsUseBuilderCheck {
    fn id(&self) -> &str {
        CHECK_ID
    }

    fn description(&self) -> &str {
        "flags Rust structs with more than the configured number of named fields that lack a builder derive"
    }

    fn configure(&self, config: &toml::Value) -> Result<Arc<dyn ConfiguredCheck>> {
        Ok(Arc::new(parse_config(config)?))
    }
}

#[async_trait]
impl ConfiguredCheck for ParsedConfig {
    async fn run(&self, changeset: &ChangeSet, tree: &dyn SourceTree) -> Result<CheckResult> {
        let mut findings = Vec::new();

        for changed_file in &changeset.changed_files {
            if matches!(changed_file.kind, ChangeKind::Deleted) {
                continue;
            }

            if !changed_file
                .path
                .extension()
                .map_or(false, |e| e == "rs")
            {
                continue;
            }

            if let Some(globs) = &self.exclude_globs {
                if globs.is_match(&changed_file.path) {
                    continue;
                }
            }

            let Ok(contents) = tree.read_file(&changed_file.path) else {
                continue;
            };
            let Ok(source) = std::str::from_utf8(&contents) else {
                continue;
            };

            let Ok(parsed_file) = syn::parse_file(source) else {
                continue;
            };

            let violations =
                collect_violations(&parsed_file.items, false, &self.builder, self.max_fields);

            for struct_name in violations {
                let line = find_struct_line(source, &struct_name);
                findings.push(Finding {
                    severity: Severity::Error,
                    message: format!(
                        "struct `{struct_name}` has more than {} named fields but lacks `#[derive({})]`",
                        self.max_fields,
                        self.builder.derive_display(),
                    ),
                    location: Some(Location {
                        path: changed_file.path.clone(),
                        line: Some(line),
                        column: Some(1),
                    }),
                    remediation: Some(format!(
                        "Add `#[derive({}::Builder)]` (and `#[builder(on(String, into))]` per the project convention) above the struct.\n\
                        Permanently exempt a file by adding it to `exclude_globs` in `CHECKS.toml`.\n\
                        Request a one-off PR exception using `BYPASS_RUST_GIANT_STRUCTS_USE_BUILDER=<specific legitimate reason>` in the PR or commit description. Only for a real exception or emergency — never use bypasses for convenience.",
                        self.builder.crate_name(),
                    )),
                    suggested_fix: None,
                });
            }
        }

        Ok(CheckResult {
            check_id: CHECK_ID.to_owned(),
            findings,
        })
    }
}

/// Recursively walk syn items, collecting the names of structs that violate the rule.
/// Skips structs and modules that are annotated with `#[cfg(test)]`.
fn collect_violations(
    items: &[syn::Item],
    in_test_mod: bool,
    builder: &BuilderKind,
    max_fields: usize,
) -> Vec<String> {
    let mut violations = Vec::new();

    for item in items {
        match item {
            syn::Item::Struct(s) => {
                if in_test_mod || has_cfg_test(&s.attrs) {
                    continue;
                }
                let syn::Fields::Named(named) = &s.fields else {
                    continue;
                };
                if named.named.len() <= max_fields {
                    continue;
                }
                if !has_required_builder(&s.attrs, builder) {
                    violations.push(s.ident.to_string());
                }
            }
            syn::Item::Mod(m) => {
                let is_test = has_cfg_test(&m.attrs);
                if let Some((_, sub_items)) = &m.content {
                    violations.extend(collect_violations(
                        sub_items,
                        in_test_mod || is_test,
                        builder,
                        max_fields,
                    ));
                }
            }
            _ => {}
        }
    }

    violations
}

fn has_cfg_test(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("cfg")
            && attr
                .parse_args::<syn::Ident>()
                .ok()
                .map_or(false, |id| id == "test")
    })
}

fn has_required_builder(attrs: &[syn::Attribute], builder: &BuilderKind) -> bool {
    for attr in attrs {
        if !attr.path().is_ident("derive") {
            continue;
        }
        let Ok(nested) = attr.parse_args_with(
            syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
        ) else {
            continue;
        };
        for path in &nested {
            let segs: Vec<_> = path.segments.iter().collect();
            match builder {
                BuilderKind::Bon => {
                    if segs.len() == 2
                        && segs[0].ident == "bon"
                        && segs[1].ident == "Builder"
                    {
                        return true;
                    }
                }
                BuilderKind::DeriveBuilder => {
                    if segs.len() == 2
                        && segs[0].ident == "derive_builder"
                        && segs[1].ident == "Builder"
                    {
                        return true;
                    }
                    // Unqualified Builder is also accepted for derive_builder
                    if segs.len() == 1 && segs[0].ident == "Builder" {
                        return true;
                    }
                }
            }
        }
    }
    false
}

/// Find the 1-based line number where `struct <name>` is declared.
/// Falls back to 1 if not found.
fn find_struct_line(source: &str, struct_name: &str) -> u32 {
    let search = format!("struct {struct_name}");
    for (i, line) in source.lines().enumerate() {
        let trimmed = line.trim_start();
        if trimmed.starts_with(&search) {
            let after = &trimmed[search.len()..];
            if after.is_empty()
                || matches!(
                    after.chars().next(),
                    Some(' ' | '\t' | '<' | '{' | '(' | '\n')
                )
            {
                return (i + 1) as u32;
            }
        }
    }
    1
}

fn parse_config(config: &toml::Value) -> Result<ParsedConfig> {
    let raw: RawConfig = config
        .clone()
        .try_into()
        .context("invalid rust-giant-structs-use-builder config")?;

    let max_fields = match raw.max_fields {
        Some(v) => usize::try_from(v).context("`max_fields` must be a non-negative integer")?,
        None => DEFAULT_MAX_FIELDS,
    };

    let builder = match raw.builder.as_deref() {
        Some("bon") | None => BuilderKind::Bon,
        Some("derive_builder") => BuilderKind::DeriveBuilder,
        Some(other) => bail!(
            "unknown `builder` value: {other:?}; expected \"bon\" or \"derive_builder\""
        ),
    };

    Ok(ParsedConfig {
        max_fields,
        builder,
        exclude_globs: parse_exclude_globs(raw.exclude_globs.as_deref())?,
    })
}

fn parse_exclude_globs(patterns: Option<&[String]>) -> Result<Option<GlobSet>> {
    let Some(patterns) = patterns else {
        return Ok(None);
    };
    if patterns.is_empty() {
        return Ok(None);
    }
    let mut builder = GlobSetBuilder::new();
    for pattern in patterns {
        let glob = Glob::new(pattern)
            .with_context(|| format!("invalid `exclude_globs` pattern: {pattern}"))?;
        builder.add(glob);
    }
    Ok(Some(
        builder
            .build()
            .context("failed to compile `exclude_globs` patterns")?,
    ))
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::Path;

    use tempfile::tempdir;

    use crate::check::Check;
    use crate::input::{ChangeKind, ChangeSet, ChangedFile};
    use crate::source_tree::LocalSourceTree;

    use super::RustGiantStructsUseBuilderCheck;

    async fn run_check(source: &str, config: toml::Value) -> Vec<String> {
        let temp = tempdir().expect("create temp dir");
        fs::write(temp.path().join("test.rs"), source).expect("write file");
        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("test.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        check
            .run(&changeset, &tree, &config)
            .await
            .expect("run check")
            .findings
            .into_iter()
            .map(|f| f.message)
            .collect()
    }

    #[tokio::test]
    async fn flags_six_field_struct_without_builder() {
        let source = r#"
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert_eq!(messages.len(), 1);
        assert!(messages[0].contains("Big"));
        assert!(messages[0].contains("bon::Builder"));
    }

    #[tokio::test]
    async fn allows_six_field_struct_with_bon_builder() {
        let source = r#"
#[derive(bon::Builder)]
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn allows_five_field_struct_without_builder() {
        let source = r#"
pub struct Small {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn ignores_tuple_struct() {
        let source = r#"
pub struct Tuple(String, String, String, String, String, String);
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn ignores_struct_in_cfg_test_mod() {
        let source = r#"
#[cfg(test)]
mod tests {
    pub struct TestHelper {
        a: String,
        b: String,
        c: String,
        d: String,
        e: String,
        f: String,
    }
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn ignores_struct_with_cfg_test_attr() {
        let source = r#"
#[cfg(test)]
pub struct TestHelper {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn flags_six_field_struct_with_derive_builder_param() {
        let source = r#"
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! { builder = "derive_builder" });
        let messages = run_check(source, config).await;
        assert_eq!(messages.len(), 1);
        assert!(messages[0].contains("derive_builder::Builder"));
    }

    #[tokio::test]
    async fn allows_six_field_struct_with_derive_builder() {
        let source = r#"
#[derive(derive_builder::Builder)]
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! { builder = "derive_builder" });
        let messages = run_check(source, config).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn respects_custom_max_fields() {
        let source = r#"
pub struct Medium {
    a: String,
    b: String,
    c: String,
}
"#;
        let config = toml::Value::Table(toml::toml! { max_fields = 2 });
        let messages = run_check(source, config).await;
        assert_eq!(messages.len(), 1);
        assert!(messages[0].contains("Medium"));
    }

    #[tokio::test]
    async fn exclude_globs_skips_matching_files() {
        let temp = tempdir().expect("create temp dir");
        fs::write(
            temp.path().join("skipped.rs"),
            r#"
pub struct Big {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#,
        )
        .expect("write file");

        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("skipped.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        let config = toml::Value::Table(toml::toml! {
            exclude_globs = ["skipped.rs"]
        });
        let result = check
            .run(&changeset, &tree, &config)
            .await
            .expect("run check");
        assert!(result.findings.is_empty());
    }
}
