use anyhow::{Context, Result, bail};
use async_trait::async_trait;
use globset::{Glob, GlobSet, GlobSetBuilder};
use serde::Deserialize;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::check::{Check, ConfiguredCheck};
use crate::exclusion::{DeclaredExclusion, ExclusionStatus};
use crate::input::{ChangeKind, ChangeSet, SourceTree};
use crate::output::{CheckResult, Finding, Location, Severity};

const CHECK_ID: &str = "rust-giant-structs-use-builder";
const DEFAULT_MAX_FIELDS: usize = 5;

/// Flags Rust structs with more named fields than `max_fields` (default 5, meaning 6+)
/// that do not carry the required builder derive. Tuple and unit structs are exempt.
/// Structs inside `#[cfg(test)]` modules and structs with `#[cfg(test)]` on themselves
/// are also exempt. Structs generated by macros are invisible to syn and thus not checked.
/// Structs that derive `clap::Parser`, `clap::Args`, or `clap::Subcommand` (or their
/// unqualified forms) are also exempt because clap owns their construction via its derive.
///
/// Grandfathering existing violations. Two knobs, with different blast radii:
///
/// * `exclude_structs` — a list of struct names/qualifiers that are exempt even though
///   they violate the rule. The file is still parsed and scanned, so a NEW giant struct
///   added to the same file is still flagged. Two entry forms:
///
///   - **Simple name** (e.g. `"WorkRun"`): scoped to the directory subtree of the
///     CHECKS.toml that owns this config. A simple name in `tools/boss/CHECKS.toml`
///     exempts `WorkRun` only in files under `tools/boss/`. It will NOT suppress the
///     same-named struct in an unrelated subtree.
///
///   - **Qualified** (e.g. `"protocol/src/types.rs::WorkRun"`): the path is resolved
///     relative to the CHECKS.toml directory. Exempts `WorkRun` only in that exact file.
///     Use this when you need pinpoint precision or want to grandfather a struct whose
///     simple name might collide with something elsewhere.
///
/// * `exclude_files` — file globs that are skipped *entirely*. Reserve this for files
///   syn cannot meaningfully check (generated code). Prefer `exclude_structs` for ordinary
///   grandfathering: a whole-file exclude permanently blinds the check to every future
///   struct in that file.
///
/// For a one-off exception in a PR, use:
///   BYPASS_RUST_GIANT_STRUCTS_USE_BUILDER=<specific reason>
/// in the PR or commit description (requires `allow_bypass = true` in policy).
pub struct RustGiantStructsUseBuilderCheck;

#[derive(Debug, Deserialize, Default)]
struct RawConfig {
    #[serde(default)]
    max_fields: Option<i64>,
    #[serde(default)]
    builder: Option<String>,
    #[serde(default, alias = "exclude_globs")]
    exclude_files: Option<Vec<String>>,
    #[serde(default)]
    exclude_structs: Option<Vec<String>>,
}

struct ParsedConfig {
    max_fields: usize,
    builder: BuilderKind,
    exclude_files: Option<GlobSet>,
    /// Simple names scoped to the config subtree (see `config_dir`).
    exclude_structs: HashSet<String>,
    /// Qualified exclusions: repo-root-relative file path → set of exempt struct names.
    exclude_structs_qualified: HashMap<PathBuf, HashSet<String>>,
    /// Directory of the CHECKS.toml that owns this config (repo-root-relative).
    /// `None` means no scope: simple-name exclusions apply to any file (backward compat).
    config_dir: Option<PathBuf>,
    /// Exclusion entries eligible for stale-exclusion auditing, each pinned to the single
    /// file it depends on. Only entries whose dependency resolves to one concrete file are
    /// listed: qualified `path::Struct` entries and literal-path `exclude_files` entries.
    /// Simple-name struct entries and glob file patterns are deliberately omitted — their
    /// dependency cannot be pinned, so they are never audited (fail safe).
    auditable_exclusions: Vec<AuditableExclusion>,
}

/// One exclusion entry the stale-exclusion audit can re-evaluate.
struct AuditableExclusion {
    /// Raw entry text exactly as written in CHECKS.toml (used to locate it and report it).
    entry: String,
    /// The single file (repo-root-relative) this exclusion depends on.
    path: PathBuf,
    kind: AuditKind,
}

enum AuditKind {
    /// A `path::Struct` exclusion: dead once the named struct no longer violates in
    /// `path` (gained a builder, dropped below the field threshold, or was removed).
    Struct(String),
    /// A literal-path `exclude_files` exclusion: dead once the file no longer exists
    /// (dangling reference). A present whole-file exclude is left load-bearing.
    File,
}

#[derive(Clone, Debug)]
enum BuilderKind {
    Bon,
    DeriveBuilder,
}

impl BuilderKind {
    fn derive_display(&self) -> &str {
        match self {
            Self::Bon => "bon::Builder",
            Self::DeriveBuilder => "derive_builder::Builder",
        }
    }

    fn crate_name(&self) -> &str {
        match self {
            Self::Bon => "bon",
            Self::DeriveBuilder => "derive_builder",
        }
    }
}

#[async_trait]
impl Check for RustGiantStructsUseBuilderCheck {
    fn id(&self) -> &str {
        CHECK_ID
    }

    fn description(&self) -> &str {
        "flags Rust structs with more than the configured number of named fields that lack a builder derive"
    }

    fn configure(&self, config: &toml::Value) -> Result<Arc<dyn ConfiguredCheck>> {
        Ok(Arc::new(parse_config(config, None)?))
    }

    fn configure_scoped(
        &self,
        config: &toml::Value,
        config_dir: Option<&Path>,
    ) -> Result<Arc<dyn ConfiguredCheck>> {
        Ok(Arc::new(parse_config(config, config_dir)?))
    }
}

#[async_trait]
impl ConfiguredCheck for ParsedConfig {
    async fn run(&self, changeset: &ChangeSet, tree: &dyn SourceTree) -> Result<CheckResult> {
        let mut findings = Vec::new();

        for changed_file in &changeset.changed_files {
            if matches!(changed_file.kind, ChangeKind::Deleted) {
                continue;
            }

            if !changed_file
                .path
                .extension()
                .map_or(false, |e| e == "rs")
            {
                continue;
            }

            if let Some(globs) = &self.exclude_files {
                let config_dir = self.config_dir.as_deref().unwrap_or(Path::new(""));
                if is_excluded(&changed_file.path, globs, config_dir) {
                    continue;
                }
            }

            let Ok(contents) = tree.read_file(&changed_file.path) else {
                continue;
            };
            let Ok(source) = std::str::from_utf8(&contents) else {
                continue;
            };

            let Ok(parsed_file) = syn::parse_file(source) else {
                continue;
            };

            // Build the effective exclusion set for this file.
            // Simple names apply only when the file is within the config subtree.
            // Qualified names apply when the entry's resolved path matches exactly.
            let in_scope = self
                .config_dir
                .as_ref()
                .map_or(true, |dir| changed_file.path.starts_with(dir));
            let mut effective_exclude: HashSet<String> = if in_scope {
                self.exclude_structs.clone()
            } else {
                HashSet::new()
            };
            if let Some(per_file) = self.exclude_structs_qualified.get(&changed_file.path) {
                effective_exclude.extend(per_file.iter().cloned());
            }

            let violations = collect_violations(
                &parsed_file.items,
                false,
                &self.builder,
                self.max_fields,
                &effective_exclude,
            );

            for struct_name in violations {
                let line = find_struct_line(source, &struct_name);
                findings.push(Finding {
                    severity: Severity::Error,
                    message: format!(
                        "struct `{struct_name}` has more than {} named fields but lacks `#[derive({})]`",
                        self.max_fields,
                        self.builder.derive_display(),
                    ),
                    location: Some(Location {
                        path: changed_file.path.clone(),
                        line: Some(line),
                        column: Some(1),
                    }),
                    remediation: Some(format!(
                        "Add `#[derive({}::Builder)]` (and `#[builder(on(String, into))]` per the project convention) above the struct.\n\
                        Permanently exempt a file by adding it to `exclude_files` in `CHECKS.toml`.",
                        self.builder.crate_name(),
                    )),
                    suggested_fix: None,
                });
            }
        }

        Ok(CheckResult {
            check_id: CHECK_ID.to_owned(),
            findings,
        })
    }

    fn declared_exclusions(&self) -> Vec<DeclaredExclusion> {
        self.auditable_exclusions
            .iter()
            .map(|exclusion| {
                DeclaredExclusion::new(exclusion.entry.clone(), vec![exclusion.path.clone()])
            })
            .collect()
    }

    async fn evaluate_exclusion(
        &self,
        exclusion: &DeclaredExclusion,
        tree: &dyn SourceTree,
    ) -> Result<ExclusionStatus> {
        let Some(spec) = self
            .auditable_exclusions
            .iter()
            .find(|candidate| candidate.entry == exclusion.entry)
        else {
            // Entry we don't recognize — fail safe.
            return Ok(ExclusionStatus::Unknown);
        };

        match &spec.kind {
            AuditKind::File => {
                // Whole-file exclude: dead only when the referenced file is gone.
                if tree.exists(&spec.path) {
                    Ok(ExclusionStatus::LoadBearing)
                } else {
                    Ok(ExclusionStatus::Stale {
                        reason: format!(
                            "the excluded file `{}` no longer exists",
                            spec.path.display()
                        ),
                    })
                }
            }
            AuditKind::Struct(name) => {
                if !tree.exists(&spec.path) {
                    return Ok(ExclusionStatus::Stale {
                        reason: format!("the file `{}` no longer exists", spec.path.display()),
                    });
                }
                let Ok(contents) = tree.read_file(&spec.path) else {
                    return Ok(ExclusionStatus::Unknown);
                };
                let Ok(source) = std::str::from_utf8(&contents) else {
                    return Ok(ExclusionStatus::Unknown);
                };
                let Ok(parsed_file) = syn::parse_file(source) else {
                    // Can't parse it now — don't claim the exclusion is dead.
                    return Ok(ExclusionStatus::Unknown);
                };

                // Re-run the rule against this file with the exclusion lifted (empty
                // exclude set). If the struct is still flagged, the exclusion is doing
                // work; otherwise it is no longer needed.
                let no_exclusions: HashSet<String> = HashSet::new();
                let violations = collect_violations(
                    &parsed_file.items,
                    false,
                    &self.builder,
                    self.max_fields,
                    &no_exclusions,
                );
                if violations.iter().any(|violation| violation == name) {
                    return Ok(ExclusionStatus::LoadBearing);
                }

                // Not a violation anymore. Distinguish "gained a builder / shrank" from
                // "the struct is gone" for a clearer message.
                let reason = if struct_declaration_line(source, name).is_some() {
                    format!("`{name}` now satisfies the builder rule without the exclusion")
                } else {
                    format!("`{name}` is no longer defined in `{}`", spec.path.display())
                };
                Ok(ExclusionStatus::Stale { reason })
            }
        }
    }
}

/// Recursively walk syn items, collecting the names of structs that violate the rule.
/// Skips structs and modules that are annotated with `#[cfg(test)]`, and structs whose
/// name is listed in `exclude_structs` (grandfathered violations).
fn collect_violations(
    items: &[syn::Item],
    in_test_mod: bool,
    builder: &BuilderKind,
    max_fields: usize,
    exclude_structs: &HashSet<String>,
) -> Vec<String> {
    let mut violations = Vec::new();

    for item in items {
        match item {
            syn::Item::Struct(s) => {
                if in_test_mod || has_cfg_test(&s.attrs) {
                    continue;
                }
                let syn::Fields::Named(named) = &s.fields else {
                    continue;
                };
                if named.named.len() <= max_fields {
                    continue;
                }
                // Clap-derived structs are exempt: clap owns their construction.
                if has_clap_derive(&s.attrs) {
                    continue;
                }
                if has_required_builder(&s.attrs, builder) {
                    continue;
                }
                let name = s.ident.to_string();
                // Grandfathered by name: still scanned, but exempt. New giant structs
                // in the same file are not exempt and will still be flagged.
                if exclude_structs.contains(&name) {
                    continue;
                }
                violations.push(name);
            }
            syn::Item::Mod(m) => {
                let is_test = has_cfg_test(&m.attrs);
                if let Some((_, sub_items)) = &m.content {
                    violations.extend(collect_violations(
                        sub_items,
                        in_test_mod || is_test,
                        builder,
                        max_fields,
                        exclude_structs,
                    ));
                }
            }
            _ => {}
        }
    }

    violations
}

fn has_cfg_test(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("cfg")
            && attr
                .parse_args::<syn::Ident>()
                .ok()
                .map_or(false, |id| id == "test")
    })
}

/// Returns true if the struct carries a clap argument-parser derive:
/// `#[derive(Parser)]`, `#[derive(Args)]`, `#[derive(Subcommand)]`,
/// or their fully-qualified forms `clap::Parser`, `clap::Args`,
/// `clap::Subcommand`. Such structs are exempt from the builder
/// requirement because clap owns their construction via its derive.
fn has_clap_derive(attrs: &[syn::Attribute]) -> bool {
    const CLAP_TRAITS: &[&str] = &["Parser", "Args", "Subcommand"];
    for attr in attrs {
        if !attr.path().is_ident("derive") {
            continue;
        }
        let Ok(nested) = attr.parse_args_with(
            syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
        ) else {
            continue;
        };
        for path in &nested {
            let segs: Vec<_> = path.segments.iter().collect();
            match segs.as_slice() {
                // Unqualified: `Parser`, `Args`, `Subcommand`
                [seg] if CLAP_TRAITS.contains(&seg.ident.to_string().as_str()) => return true,
                // Qualified: `clap::Parser`, `clap::Args`, `clap::Subcommand`
                [krate, trait_seg]
                    if krate.ident == "clap"
                        && CLAP_TRAITS.contains(&trait_seg.ident.to_string().as_str()) =>
                {
                    return true
                }
                _ => {}
            }
        }
    }
    false
}

fn has_required_builder(attrs: &[syn::Attribute], builder: &BuilderKind) -> bool {
    for attr in attrs {
        if !attr.path().is_ident("derive") {
            continue;
        }
        let Ok(nested) = attr.parse_args_with(
            syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
        ) else {
            continue;
        };
        for path in &nested {
            let segs: Vec<_> = path.segments.iter().collect();
            match builder {
                BuilderKind::Bon => {
                    if segs.len() == 2
                        && segs[0].ident == "bon"
                        && segs[1].ident == "Builder"
                    {
                        return true;
                    }
                }
                BuilderKind::DeriveBuilder => {
                    if segs.len() == 2
                        && segs[0].ident == "derive_builder"
                        && segs[1].ident == "Builder"
                    {
                        return true;
                    }
                    // Unqualified Builder is also accepted for derive_builder
                    if segs.len() == 1 && segs[0].ident == "Builder" {
                        return true;
                    }
                }
            }
        }
    }
    false
}

/// Find the 1-based line number where `struct <name>` is declared, or `None` if the
/// declaration can't be located. Handles a leading visibility modifier (`pub`,
/// `pub(crate)`, `pub(super)`, `pub(in path)`) so that `pub struct Foo` resolves to the
/// right line.
fn struct_declaration_line(source: &str, struct_name: &str) -> Option<u32> {
    let search = format!("struct {struct_name}");
    for (i, line) in source.lines().enumerate() {
        let candidate = strip_visibility(line.trim_start());
        if let Some(after) = candidate.strip_prefix(&search) {
            // Ensure we matched the whole ident, not a prefix of a longer name.
            if after.is_empty()
                || matches!(after.chars().next(), Some(' ' | '\t' | '<' | '{' | '('))
            {
                return Some((i + 1) as u32);
            }
        }
    }
    None
}

/// Like [`struct_declaration_line`] but falls back to line 1 when the declaration can't
/// be located, for use as a finding location.
fn find_struct_line(source: &str, struct_name: &str) -> u32 {
    struct_declaration_line(source, struct_name).unwrap_or(1)
}

/// Strip a leading `pub` / `pub(...)` visibility modifier (and following
/// whitespace) from an already-`trim_start`ed line. Leaves the line untouched
/// when there is no visibility keyword (so `published` is not mistaken for `pub`).
fn strip_visibility(line: &str) -> &str {
    let Some(rest) = line.strip_prefix("pub") else {
        return line;
    };
    match rest.chars().next() {
        // Restricted visibility: `pub(crate)`, `pub(super)`, `pub(in path)`.
        Some('(') => match rest.find(')') {
            Some(close) => rest[close + 1..].trim_start(),
            None => line,
        },
        // Plain `pub ` followed by whitespace.
        Some(c) if c.is_whitespace() => rest.trim_start(),
        // Something like `pubfoo` — not the visibility keyword.
        _ => line,
    }
}

fn parse_config(config: &toml::Value, config_dir: Option<&Path>) -> Result<ParsedConfig> {
    let raw: RawConfig = config
        .clone()
        .try_into()
        .context("invalid rust-giant-structs-use-builder config")?;

    let max_fields = match raw.max_fields {
        Some(v) => usize::try_from(v).context("`max_fields` must be a non-negative integer")?,
        None => DEFAULT_MAX_FIELDS,
    };

    let builder = match raw.builder.as_deref() {
        Some("bon") | None => BuilderKind::Bon,
        Some("derive_builder") => BuilderKind::DeriveBuilder,
        Some(other) => bail!(
            "unknown `builder` value: {other:?}; expected \"bon\" or \"derive_builder\""
        ),
    };

    let mut exclude_structs: HashSet<String> = HashSet::new();
    let mut exclude_structs_qualified: HashMap<PathBuf, HashSet<String>> = HashMap::new();
    let mut auditable_exclusions: Vec<AuditableExclusion> = Vec::new();

    let resolve = |path_part: &str| -> PathBuf {
        match config_dir {
            Some(dir) => dir.join(path_part),
            None => PathBuf::from(path_part),
        }
    };

    let raw_exclude_files = raw.exclude_files.clone().unwrap_or_default();
    for entry in raw.exclude_structs.unwrap_or_default() {
        // Qualified form: `relative/path.rs::StructName`
        // Path is relative to the CHECKS.toml directory (config_dir).
        if let Some(sep) = entry.rfind("::") {
            let path_part = &entry[..sep];
            let name_part = entry[sep + 2..].to_owned();
            let resolved = resolve(path_part);
            // A qualified entry pins exactly one file and one struct, so it is auditable:
            // re-evaluate `name_part` in `resolved` with the exclusion lifted.
            auditable_exclusions.push(AuditableExclusion {
                entry: entry.clone(),
                path: resolved.clone(),
                kind: AuditKind::Struct(name_part.clone()),
            });
            exclude_structs_qualified
                .entry(resolved)
                .or_default()
                .insert(name_part);
        } else {
            // Simple form: scoped to the config subtree at runtime. The struct could live
            // in any file in the subtree, so the dependency can't be pinned — not audited.
            exclude_structs.insert(entry);
        }
    }

    // Literal-path `exclude_files` entries depend on exactly one file and go stale when
    // that file is deleted. Glob patterns can't be pinned to a single path, so they are
    // not audited.
    for pattern in &raw_exclude_files {
        if is_literal_path(pattern) {
            auditable_exclusions.push(AuditableExclusion {
                entry: pattern.clone(),
                path: resolve(pattern),
                kind: AuditKind::File,
            });
        }
    }

    Ok(ParsedConfig {
        max_fields,
        builder,
        exclude_files: parse_exclude_files(raw.exclude_files.as_deref())?,
        exclude_structs,
        exclude_structs_qualified,
        config_dir: config_dir.map(|p| p.to_path_buf()),
        auditable_exclusions,
    })
}

/// A pattern with no glob metacharacters resolves to a single concrete file path.
fn is_literal_path(pattern: &str) -> bool {
    !pattern.contains(['*', '?', '[', ']', '{', '}', '!'])
}

fn parse_exclude_files(patterns: Option<&[String]>) -> Result<Option<GlobSet>> {
    let Some(patterns) = patterns else {
        return Ok(None);
    };
    if patterns.is_empty() {
        return Ok(None);
    }
    let mut builder = GlobSetBuilder::new();
    for pattern in patterns {
        let glob = Glob::new(pattern)
            .with_context(|| format!("invalid `exclude_files` pattern: {pattern}"))?;
        builder.add(glob);
    }
    Ok(Some(
        builder
            .build()
            .context("failed to compile `exclude_files` patterns")?,
    ))
}

/// Returns true if `path` is within `config_dir` and matches `globs` (relative to config_dir).
/// Files outside the config_dir subtree are never excluded.
fn is_excluded(path: &Path, globs: &GlobSet, config_dir: &Path) -> bool {
    let Ok(relative) = path.strip_prefix(config_dir) else {
        return false;
    };
    globs.is_match(relative)
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::Path;

    use tempfile::tempdir;

    use crate::check::{Check, ConfiguredCheck};
    use crate::exclusion::{DeclaredExclusion, ExclusionStatus};
    use crate::input::{ChangeKind, ChangeSet, ChangedFile};
    use crate::output::Finding;
    use crate::source_tree::LocalSourceTree;

    use super::RustGiantStructsUseBuilderCheck;

    async fn run_check_findings(source: &str, config: toml::Value) -> Vec<Finding> {
        let temp = tempdir().expect("create temp dir");
        fs::write(temp.path().join("test.rs"), source).expect("write file");
        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("test.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        check
            .run(&changeset, &tree, &config)
            .await
            .expect("run check")
            .findings
    }

    async fn run_check(source: &str, config: toml::Value) -> Vec<String> {
        run_check_findings(source, config)
            .await
            .into_iter()
            .map(|f| f.message)
            .collect()
    }

    #[tokio::test]
    async fn flags_six_field_struct_without_builder() {
        let source = r#"
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert_eq!(messages.len(), 1);
        assert!(messages[0].contains("Big"));
        assert!(messages[0].contains("bon::Builder"));
    }

    #[tokio::test]
    async fn allows_six_field_struct_with_bon_builder() {
        let source = r#"
#[derive(bon::Builder)]
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn allows_five_field_struct_without_builder() {
        let source = r#"
pub struct Small {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn ignores_tuple_struct() {
        let source = r#"
pub struct Tuple(String, String, String, String, String, String);
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn ignores_struct_in_cfg_test_mod() {
        let source = r#"
#[cfg(test)]
mod tests {
    pub struct TestHelper {
        a: String,
        b: String,
        c: String,
        d: String,
        e: String,
        f: String,
    }
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn ignores_struct_with_cfg_test_attr() {
        let source = r#"
#[cfg(test)]
pub struct TestHelper {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn flags_six_field_struct_with_derive_builder_param() {
        let source = r#"
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! { builder = "derive_builder" });
        let messages = run_check(source, config).await;
        assert_eq!(messages.len(), 1);
        assert!(messages[0].contains("derive_builder::Builder"));
    }

    #[tokio::test]
    async fn allows_six_field_struct_with_derive_builder() {
        let source = r#"
#[derive(derive_builder::Builder)]
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! { builder = "derive_builder" });
        let messages = run_check(source, config).await;
        assert!(messages.is_empty());
    }

    #[tokio::test]
    async fn respects_custom_max_fields() {
        let source = r#"
pub struct Medium {
    a: String,
    b: String,
    c: String,
}
"#;
        let config = toml::Value::Table(toml::toml! { max_fields = 2 });
        let messages = run_check(source, config).await;
        assert_eq!(messages.len(), 1);
        assert!(messages[0].contains("Medium"));
    }

    #[tokio::test]
    async fn exclude_files_skips_matching_files() {
        let temp = tempdir().expect("create temp dir");
        fs::write(
            temp.path().join("skipped.rs"),
            r#"
pub struct Big {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#,
        )
        .expect("write file");

        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("skipped.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        let config = toml::Value::Table(toml::toml! {
            exclude_files = ["skipped.rs"]
        });
        let result = check
            .run(&changeset, &tree, &config)
            .await
            .expect("run check");
        assert!(result.findings.is_empty());
    }

    #[tokio::test]
    async fn exclude_globs_alias_still_works() {
        let temp = tempdir().expect("create temp dir");
        fs::write(
            temp.path().join("skipped.rs"),
            r#"
pub struct Big {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#,
        )
        .expect("write file");

        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("skipped.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        let config = toml::Value::Table(toml::toml! {
            exclude_globs = ["skipped.rs"]
        });
        let result = check
            .run(&changeset, &tree, &config)
            .await
            .expect("run check");
        assert!(result.findings.is_empty());
    }

    #[tokio::test]
    async fn exclude_structs_exempts_named_struct() {
        let source = r#"
pub struct Grandfathered {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["Grandfathered"]
        });
        let messages = run_check(source, config).await;
        assert!(messages.is_empty());
    }

    /// Regression test for the `CreateAttentionInput` miss: when a file holds a
    /// grandfathered giant struct (exempt by name) AND a new giant struct, the new
    /// one is still flagged. Previously the whole file was skipped via `exclude_globs`,
    /// so the new struct slipped through.
    #[tokio::test]
    async fn flags_new_giant_struct_even_when_sibling_is_grandfathered() {
        let source = r#"
pub struct Grandfathered {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}

pub struct FreshlyAdded {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["Grandfathered"]
        });
        let messages = run_check(source, config).await;
        assert_eq!(messages.len(), 1);
        assert!(messages[0].contains("FreshlyAdded"));
        assert!(!messages[0].contains("Grandfathered"));
    }

    /// The shape of `CreateAttentionInput` from boss-protocol: `#[derive(... Default ...)]`,
    /// many `Option<String>` fields each carrying `#[serde(...)]`, and no builder derive.
    /// This is exactly the struct the check failed to flag (because its file was in
    /// `exclude_globs`). With the file scanned, the shape itself must be flagged.
    #[tokio::test]
    async fn flags_create_attention_input_shape() {
        let source = r#"
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateAttentionInput {
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub association_project_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub association_task_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_kind: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_text: Option<String>,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert_eq!(messages.len(), 1);
        assert!(messages[0].contains("CreateAttentionInput"));
        assert!(messages[0].contains("bon::Builder"));
    }

    /// `find_struct_line` must resolve the declaration line for `pub struct` (and
    /// restricted visibilities), not fall back to line 1.
    #[tokio::test]
    async fn reports_declaration_line_for_pub_struct() {
        let source = r#"// line 1
// line 2
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let findings = run_check_findings(source, toml::Value::Table(toml::Table::new())).await;
        assert_eq!(findings.len(), 1);
        let line = findings[0]
            .location
            .as_ref()
            .and_then(|l| l.line)
            .expect("finding has a line");
        // The raw string has no leading newline, so `// line 1` is line 1 and
        // `pub struct Big` is line 4. Before the fix this fell back to 1.
        assert_eq!(line, 4);
    }

    #[tokio::test]
    async fn reports_declaration_line_for_restricted_visibility() {
        let source = r#"
pub(crate) struct Big {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let findings = run_check_findings(source, toml::Value::Table(toml::Table::new())).await;
        assert_eq!(findings.len(), 1);
        let line = findings[0]
            .location
            .as_ref()
            .and_then(|l| l.line)
            .expect("finding has a line");
        assert_eq!(line, 2);
    }

    // --- Scoped exclusion tests ---

    /// Helper that runs the check with an explicit config_dir scope.
    /// The changed file is always `test.rs` relative to a fresh temp dir.
    async fn run_check_scoped(
        source: &str,
        config: toml::Value,
        config_dir: Option<&Path>,
    ) -> Vec<String> {
        let temp = tempdir().expect("create temp dir");
        fs::write(temp.path().join("test.rs"), source).expect("write file");
        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("test.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        let configured = check
            .configure_scoped(&config, config_dir)
            .expect("configure_scoped");
        configured
            .run(&changeset, &tree)
            .await
            .expect("run check")
            .findings
            .into_iter()
            .map(|f| f.message)
            .collect()
    }

    /// A simple-name exclusion with no config_dir scope (backward compat) still applies globally.
    #[tokio::test]
    async fn simple_name_no_scope_applies_globally() {
        let source = r#"
pub struct Grandfathered {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["Grandfathered"]
        });
        // No config_dir: backward-compat, exclusion applies to any file.
        let messages = run_check_scoped(source, config, None).await;
        assert!(messages.is_empty(), "expected no findings, got {messages:?}");
    }

    /// A simple-name exclusion is NOT applied when the changed file is outside the config subtree.
    #[tokio::test]
    async fn simple_name_out_of_scope_is_not_exempt() {
        let source = r#"
pub struct Grandfathered {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["Grandfathered"]
        });
        // config_dir = "tools/other" → test.rs is outside that subtree.
        let messages =
            run_check_scoped(source, config, Some(Path::new("tools/other"))).await;
        assert_eq!(messages.len(), 1, "expected Grandfathered to be flagged");
        assert!(messages[0].contains("Grandfathered"));
    }

    /// A simple-name exclusion IS applied when the changed file is within the config subtree.
    #[tokio::test]
    async fn simple_name_in_scope_is_exempt() {
        let source = r#"
pub struct Grandfathered {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["Grandfathered"]
        });
        // The changeset file path is "test.rs"; an empty-string config_dir is the repo root,
        // so every file is in scope.
        let messages = run_check_scoped(source, config, Some(Path::new(""))).await;
        assert!(messages.is_empty(), "expected no findings, got {messages:?}");
    }

    /// A qualified entry (`path::StructName`) exempts the named struct only in that exact file.
    #[tokio::test]
    async fn qualified_entry_exempts_struct_in_matching_file() {
        let source = r#"
pub struct Grandfathered {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        // Qualified path relative to config_dir; with no config_dir the path is repo-root-relative.
        // The changeset file is "test.rs", so entry "test.rs::Grandfathered" matches.
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["test.rs::Grandfathered"]
        });
        let messages = run_check_scoped(source, config, None).await;
        assert!(messages.is_empty(), "expected no findings, got {messages:?}");
    }

    /// A qualified entry for a DIFFERENT file does not exempt the struct in the current file.
    #[tokio::test]
    async fn qualified_entry_does_not_match_different_file() {
        let source = r#"
pub struct Grandfathered {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["other.rs::Grandfathered"]
        });
        let messages = run_check_scoped(source, config, None).await;
        assert_eq!(messages.len(), 1, "expected Grandfathered to be flagged");
        assert!(messages[0].contains("Grandfathered"));
    }

    /// A qualified entry with config_dir resolves relative to that directory.
    /// File at changeset path "sub/test.rs" matches entry "test.rs::Grandfathered"
    /// when config_dir is "sub".
    #[tokio::test]
    async fn qualified_entry_resolves_relative_to_config_dir() {
        let source = r#"
pub struct Grandfathered {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        let temp = tempdir().expect("create temp dir");
        std::fs::create_dir_all(temp.path().join("sub")).expect("mkdir sub");
        fs::write(temp.path().join("sub/test.rs"), source).expect("write file");
        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("sub/test.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        // "test.rs::Grandfathered" + config_dir="sub" → resolves to "sub/test.rs"
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["test.rs::Grandfathered"]
        });
        let configured = check
            .configure_scoped(&config, Some(Path::new("sub")))
            .expect("configure_scoped");
        let messages: Vec<String> = configured
            .run(&changeset, &tree)
            .await
            .expect("run check")
            .findings
            .into_iter()
            .map(|f| f.message)
            .collect();
        assert!(
            messages.is_empty(),
            "expected no findings (qualified path resolved relative to config_dir), got {messages:?}"
        );
    }

    #[tokio::test]
    async fn exclude_files_does_not_apply_outside_config_dir_subtree() {
        let source = r#"
pub struct Big {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        let temp = tempdir().expect("create temp dir");
        fs::write(temp.path().join("test.rs"), source).expect("write file");
        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");

        // "test.rs" at root is NOT in "sub/dir" subtree; pattern "test.rs" should not match it.
        let configured = check
            .configure_scoped(
                &toml::Value::Table(toml::toml! {
                    exclude_files = ["test.rs"]
                }),
                Some(Path::new("sub/dir")),
            )
            .expect("configure_scoped");

        let result = configured
            .run(
                &ChangeSet::new(vec![ChangedFile {
                    path: Path::new("test.rs").to_path_buf(),
                    kind: ChangeKind::Modified,
                    old_path: None,
                }]),
                &tree,
            )
            .await
            .expect("run check");

        assert_eq!(result.findings.len(), 1, "file outside config_dir should not be excluded");
    }

    #[tokio::test]
    async fn clap_parser_struct_is_exempt() {
        let source = r#"
#[derive(Debug, clap::Parser)]
pub struct Cli {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(
            messages.is_empty(),
            "clap::Parser struct should be exempt, got {messages:?}"
        );
    }

    #[tokio::test]
    async fn clap_args_struct_is_exempt() {
        let source = r#"
#[derive(Debug, Clone, Args)]
pub struct TaskArgs {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(
            messages.is_empty(),
            "unqualified Args struct should be exempt, got {messages:?}"
        );
    }

    #[tokio::test]
    async fn clap_subcommand_struct_is_exempt() {
        let source = r#"
#[derive(Debug, clap::Subcommand)]
pub struct Commands {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert!(
            messages.is_empty(),
            "clap::Subcommand struct should be exempt, got {messages:?}"
        );
    }

    #[tokio::test]
    async fn non_clap_giant_struct_is_still_flagged() {
        let source = r#"
#[derive(Debug, Clone)]
pub struct PlainBig {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
    f: String,
}
"#;
        let messages = run_check(source, toml::Value::Table(toml::Table::new())).await;
        assert_eq!(
            messages.len(),
            1,
            "plain giant struct should still be flagged"
        );
        assert!(messages[0].contains("PlainBig"));
    }

    /// The exact shape this repo's `exclude_globs` → `exclude_structs` migration relies on:
    /// a file under the config subtree holds a giant struct grandfathered by a *qualified*
    /// entry AND a newly-added giant struct. The grandfathered one stays exempt; the new
    /// one IS flagged. A whole-file `exclude_globs` entry would have suppressed both — that
    /// is precisely the blind spot the migration removes. Mirrors the real config layout:
    /// config_dir `tools/boss`, file `tools/boss/engine/src/app.rs`, entry
    /// `engine/src/app.rs::ServerState`.
    #[tokio::test]
    async fn qualified_grandfather_exempts_known_struct_but_flags_new_sibling() {
        let source = r#"
pub struct ServerState {
    a: String, b: String, c: String, d: String, e: String, f: String,
}

pub struct FreshlyAdded {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        let temp = tempdir().expect("create temp dir");
        std::fs::create_dir_all(temp.path().join("tools/boss/engine/src"))
            .expect("mkdir tools/boss/engine/src");
        fs::write(temp.path().join("tools/boss/engine/src/app.rs"), source).expect("write file");
        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("tools/boss/engine/src/app.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        // Qualified entry resolved relative to config_dir `tools/boss` →
        // `tools/boss/engine/src/app.rs`, exempting only `ServerState` there.
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["engine/src/app.rs::ServerState"]
        });
        let configured = check
            .configure_scoped(&config, Some(Path::new("tools/boss")))
            .expect("configure_scoped");
        let messages: Vec<String> = configured
            .run(&changeset, &tree)
            .await
            .expect("run check")
            .findings
            .into_iter()
            .map(|f| f.message)
            .collect();
        assert_eq!(messages.len(), 1, "expected only the new struct flagged, got {messages:?}");
        assert!(messages[0].contains("FreshlyAdded"));
        assert!(!messages[0].contains("ServerState"));
    }

    /// Counterpart to the qualified-grandfather test: the same struct name in a *different*
    /// file is NOT exempted by a qualified entry, so moving/renaming a grandfathered struct
    /// out of its declared file re-arms the check. Guards the "only the known-existing
    /// violation is exempt" property the migration is meant to deliver.
    #[tokio::test]
    async fn qualified_grandfather_does_not_exempt_same_name_in_other_file() {
        let source = r#"
pub struct ServerState {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;
        let temp = tempdir().expect("create temp dir");
        std::fs::create_dir_all(temp.path().join("tools/boss/engine/src"))
            .expect("mkdir tools/boss/engine/src");
        // Same struct name, but in a different file than the qualified entry points at.
        fs::write(temp.path().join("tools/boss/engine/src/other.rs"), source).expect("write file");
        let check = RustGiantStructsUseBuilderCheck;
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let changeset = ChangeSet::new(vec![ChangedFile {
            path: Path::new("tools/boss/engine/src/other.rs").to_path_buf(),
            kind: ChangeKind::Modified,
            old_path: None,
        }]);
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["engine/src/app.rs::ServerState"]
        });
        let configured = check
            .configure_scoped(&config, Some(Path::new("tools/boss")))
            .expect("configure_scoped");
        let messages: Vec<String> = configured
            .run(&changeset, &tree)
            .await
            .expect("run check")
            .findings
            .into_iter()
            .map(|f| f.message)
            .collect();
        assert_eq!(messages.len(), 1, "expected ServerState flagged in the wrong file, got {messages:?}");
        assert!(messages[0].contains("ServerState"));
    }

    // --- Stale-exclusion auditing tests ---

    const SIX_FIELD_STRUCT: &str = r#"
pub struct Big {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;

    const SIX_FIELD_STRUCT_WITH_BUILDER: &str = r#"
#[derive(bon::Builder)]
pub struct Big {
    a: String, b: String, c: String, d: String, e: String, f: String,
}
"#;

    fn configured(
        config: toml::Value,
        config_dir: Option<&Path>,
    ) -> std::sync::Arc<dyn ConfiguredCheck> {
        RustGiantStructsUseBuilderCheck
            .configure_scoped(&config, config_dir)
            .expect("configure_scoped")
    }

    fn sorted_entries(declared: &[DeclaredExclusion]) -> Vec<String> {
        let mut entries: Vec<String> = declared.iter().map(|d| d.entry.clone()).collect();
        entries.sort();
        entries
    }

    /// Only qualified struct entries and literal-path file entries are auditable. Simple
    /// names (dependency can't be pinned) and glob file patterns are omitted (fail safe).
    #[test]
    fn declared_exclusions_lists_only_pinnable_entries() {
        let config = toml::Value::Table(toml::toml! {
            exclude_structs = ["SimpleName", "a.rs::Qualified"]
            exclude_files = ["literal.rs", "generated/*.rs"]
        });
        let check = configured(config, Some(Path::new("sub")));
        let declared = check.declared_exclusions();

        assert_eq!(
            sorted_entries(&declared),
            vec!["a.rs::Qualified".to_owned(), "literal.rs".to_owned()],
        );

        // Dependency paths resolve relative to the config_dir.
        let qualified = declared
            .iter()
            .find(|d| d.entry == "a.rs::Qualified")
            .expect("qualified entry declared");
        assert_eq!(qualified.depends_on, vec![Path::new("sub/a.rs").to_path_buf()]);
        let literal = declared
            .iter()
            .find(|d| d.entry == "literal.rs")
            .expect("literal file entry declared");
        assert_eq!(literal.depends_on, vec![Path::new("sub/literal.rs").to_path_buf()]);
    }

    /// A struct exclusion is load-bearing while the struct still violates without it.
    #[tokio::test]
    async fn evaluate_exclusion_load_bearing_when_struct_still_violates() {
        let temp = tempdir().expect("create temp dir");
        fs::write(temp.path().join("test.rs"), SIX_FIELD_STRUCT).expect("write file");
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let check = configured(
            toml::Value::Table(toml::toml! { exclude_structs = ["test.rs::Big"] }),
            Some(Path::new("")),
        );
        let exclusion = DeclaredExclusion::new("test.rs::Big", vec!["test.rs".into()]);
        let status = check
            .evaluate_exclusion(&exclusion, &tree)
            .await
            .expect("evaluate");
        assert_eq!(status, ExclusionStatus::LoadBearing);
    }

    /// Once the struct gains a builder, the exclusion is stale (semantic case 2).
    #[tokio::test]
    async fn evaluate_exclusion_stale_when_struct_gains_builder() {
        let temp = tempdir().expect("create temp dir");
        fs::write(temp.path().join("test.rs"), SIX_FIELD_STRUCT_WITH_BUILDER).expect("write file");
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let check = configured(
            toml::Value::Table(toml::toml! { exclude_structs = ["test.rs::Big"] }),
            Some(Path::new("")),
        );
        let exclusion = DeclaredExclusion::new("test.rs::Big", vec!["test.rs".into()]);
        let status = check
            .evaluate_exclusion(&exclusion, &tree)
            .await
            .expect("evaluate");
        match status {
            ExclusionStatus::Stale { reason } => {
                assert!(reason.contains("satisfies"), "unexpected reason: {reason}");
            }
            other => panic!("expected stale, got {other:?}"),
        }
    }

    /// A struct exclusion whose file was deleted is stale (dangling reference).
    #[tokio::test]
    async fn evaluate_exclusion_stale_when_struct_file_deleted() {
        let temp = tempdir().expect("create temp dir");
        // Do not create test.rs — it was deleted in the diff.
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let check = configured(
            toml::Value::Table(toml::toml! { exclude_structs = ["test.rs::Big"] }),
            Some(Path::new("")),
        );
        let exclusion = DeclaredExclusion::new("test.rs::Big", vec!["test.rs".into()]);
        let status = check
            .evaluate_exclusion(&exclusion, &tree)
            .await
            .expect("evaluate");
        match status {
            ExclusionStatus::Stale { reason } => {
                assert!(reason.contains("no longer exists"), "unexpected reason: {reason}");
            }
            other => panic!("expected stale, got {other:?}"),
        }
    }

    /// A struct exclusion whose named struct no longer appears is stale.
    #[tokio::test]
    async fn evaluate_exclusion_stale_when_struct_removed() {
        let temp = tempdir().expect("create temp dir");
        fs::write(temp.path().join("test.rs"), "pub struct Other { a: u8 }\n").expect("write file");
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let check = configured(
            toml::Value::Table(toml::toml! { exclude_structs = ["test.rs::Big"] }),
            Some(Path::new("")),
        );
        let exclusion = DeclaredExclusion::new("test.rs::Big", vec!["test.rs".into()]);
        let status = check
            .evaluate_exclusion(&exclusion, &tree)
            .await
            .expect("evaluate");
        match status {
            ExclusionStatus::Stale { reason } => {
                assert!(reason.contains("no longer defined"), "unexpected reason: {reason}");
            }
            other => panic!("expected stale, got {other:?}"),
        }
    }

    /// A literal `exclude_files` entry is load-bearing while the file exists, and stale
    /// once it is deleted (dangling reference, case 1).
    #[tokio::test]
    async fn evaluate_exclusion_file_entry_tracks_existence() {
        let temp = tempdir().expect("create temp dir");
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let check = configured(
            toml::Value::Table(toml::toml! { exclude_files = ["gen.rs"] }),
            Some(Path::new("")),
        );
        let exclusion = DeclaredExclusion::new("gen.rs", vec!["gen.rs".into()]);

        // Missing file => stale.
        let status = check
            .evaluate_exclusion(&exclusion, &tree)
            .await
            .expect("evaluate");
        assert!(matches!(status, ExclusionStatus::Stale { .. }));

        // Present file => load-bearing.
        fs::write(temp.path().join("gen.rs"), "// generated\n").expect("write file");
        let status = check
            .evaluate_exclusion(&exclusion, &tree)
            .await
            .expect("evaluate");
        assert_eq!(status, ExclusionStatus::LoadBearing);
    }

    /// An entry the check does not recognize is never reported (fail safe).
    #[tokio::test]
    async fn evaluate_exclusion_unknown_for_unrecognized_entry() {
        let temp = tempdir().expect("create temp dir");
        let tree = LocalSourceTree::new(temp.path()).expect("create tree");
        let check = configured(
            toml::Value::Table(toml::toml! { exclude_structs = ["test.rs::Big"] }),
            Some(Path::new("")),
        );
        let exclusion = DeclaredExclusion::new("nope.rs::Ghost", vec!["nope.rs".into()]);
        let status = check
            .evaluate_exclusion(&exclusion, &tree)
            .await
            .expect("evaluate");
        assert_eq!(status, ExclusionStatus::Unknown);
    }
}
